"""
Core modules for hybrid dynamics analysis.

This module provides the foundational classes and utilities for hybrid system simulation,
grid-based analysis, cubification, graph analysis, and visualization.
"""

# Core classes
# Grid and cubification
from .box import Box, SquareBox
from .cubifier import DatasetCubifier
from .data_utils import GridEvaluationResult
from .evaluation import evaluate_grid
from .grid import Grid

# Utilities
from .grid_utils import *
from .hybrid_boxmap import HybridBoxMap
from .cmgdb_suspension_boxmap import (
    CMGDBSuspensionBoxMap,
    SINGLE_HANDLE_BRIDGE_ALGORITHM,
    SINGLE_HANDLE_BRIDGE_ASSUMPTIONS,
    SamplingFailure,
    SingleHandleBridgeDiagnostic,
    SingleHandleBridgeProbe,
    SourceBoxMapDiagnostic,
    SuspensionAtlasCharts,
    SuspensionBoxMapDiagnostics,
    SuspensionStratum,
    TaggedRectangle,
    build_cmgdb_atlas_model,
)
from .hybrid_system import HybridSystem
from .hybrid_time import HybridTime, HybridTimeInterval
from .hybrid_trajectory import HybridTrajectory, TrajectorySegment
from .implicit_phase_scc import (
    FullSCCReconstruction,
    PhaseDescriptor,
    PhaseGadgetDescriptor,
    PhasePathDescriptor,
    VirtualPhaseNode,
    build_base_macro_graph,
    reconstruct_from_base_descriptors,
    reconstruct_full_scc_condensation,
)
from .fixed_time_suspension_grid import (
    FixedTimeSuspensionGridResult,
    GridResetHandle,
    GridSuspensionIngredients,
    SuspensionCemeteryCell,
    compute_fixed_time_suspension_grid,
)
from .fixed_time_relation_audit import (
    AuditedCell,
    AugmentedQuotientIncidence,
    CellSetConnectivity,
    EndpointCoverageAudit,
    EndpointCoverageWitness,
    EndpointEvaluationFailure,
    EndpointProbe,
    RelationAuditFailure,
    RelationConnectivityAudit,
    audit_cell_sets_connectivity,
    audit_dense_base_endpoints,
    audit_endpoint_probes,
    audit_relation_image_connectivity,
)
from .hybrid_morse_plot import (
    CMGDB_MORSE_PALETTE,
    SCIENTIFIC_MORSE_PALETTE,
    HybridMorseComponent,
    HybridMorsePlot,
    PlotHybridMorseSets,
    hybrid_morse_components,
    hybrid_morse_hasse,
    plot_hybrid_morse_sets,
    save_hybrid_morse_figure,
)
from .atlas_morse_plot import (
    ATLAS_MORSE_PLOT_SCHEMA,
    PHYSICAL_CONLEY_FINITE_RELATION_AUDIT_SCHEMA,
    AtlasFiniteRelationIndexAnnotations,
    AtlasHybridMorseComponent,
    AtlasHybridMorsePlot,
    AtlasMorseBox,
    AtlasMorseNode,
    AtlasMorsePlotData,
    atlas_morse_components,
    atlas_morse_hasse,
    atlas_morse_plot_data_payload,
    extract_atlas_morse_plot_data,
    load_atlas_morse_plot_data,
    load_atlas_finite_relation_index_annotations,
    plot_atlas_hybrid_morse_sets,
    save_atlas_morse_plot_data,
)

# Graph analysis
from .morse_graph import create_morse_graph

# MultiGrid framework
from .multigrid import MultiGrid, MultiGridBoxMap
from .sampled_suspension import (
    AugmentedCell,
    BaseSuspensionSample,
    BaseCell,
    HandleSuspensionSample,
    PhaseCell,
    PhaseOnlyRecurrentComponentError,
    RecurrentMorseCollapseDiagnostic,
    SuspensionSample,
    assert_recurrent_morse_equivalence,
    build_augmented_outer_graph,
    collapse_phase_paths,
    crossing_completed_state,
    diagnose_recurrent_morse_collapse,
    locate_augmented_cells,
    sample_suspension_trajectory,
    simulate_crossing_completed_state,
    simulate_suspension_endpoint,
)
from .suspension_complex import (
    CMGDBCellRelationPayload,
    CMGDBRelativeHomologyPayload,
    CellularAttachmentMap,
    CellularChainMap,
    CellularMapBetweenComplexes,
    CellularResetMap,
    CrossComplexAcyclicCarrier,
    CubicalCell,
    CubicalGridComplex,
    CubicalHyperplaneAttachmentAudit,
    DoubleMappingCylinderComplex,
    DoubleMappingCylinderHandle,
    FiniteCellComplex,
    FixedTimeCarrier,
    FixedTimeCellRelation,
    GuardPrismCell,
    PhaseCellRegistry,
    PhaseSliceCell,
    RelativeCellPair,
    RelativeHomologyBasis,
    ResetHandle,
    SampledSuspensionCellAdapter,
    SparseCubicalGridComplex,
    SuspensionBaseCell,
    SuspensionCellComplex,
    audit_cubical_hyperplane_attachment,
    build_cubical_grid_complex,
)
from .atlas_conley import (
    AffineBoundaryEmbedding2D,
    AtlasGoodCoverError,
    AtlasMappingCylinderConleyPreparation,
    AtlasMappingCylinderRegistry,
    AtlasMappingCylinderRelativePair,
    AtlasMappingCylinderTopCell,
    AtlasNerveSimplex,
    AtlasPhysicalConleyPreparation2D,
    AtlasQuotientNerveComplex2D,
    AtlasRectangleCell2D,
    AtlasRelativeIndexPair2D,
    AtlasResetGluing2D,
    AtlasSeamSubcomplexAudit2D,
    PhysicalConleyCertificationError,
    QuotientIntersectionAudit2D,
    QuotientRectangleRepresentative2D,
    RawAtlasCellCover2D,
    atlas_cells_from_morse_graph,
    atlas_cells_from_phase_space,
    prepare_atlas_physical_conley_2d,
    prepare_atlas_mapping_cylinder_conley,
    prepare_atlas_relation_conley_2d,
)

from .suspension_grid import (
    DyadicBaseWindow,
    GeneratorKey,
    GuardResetSpec,
    LocatedPoints,
    SuspensionGrid,
    SuspensionGridCheck,
    UnsupportedSuspensionGridError,
    build_suspension_grid,
    check_suspension_grid,
)
from .suspension_grid_relation import (
    EndpointBatch,
    SuspensionFlow,
    SuspensionGridProblem,
    SuspensionGridRelation,
    SuspensionMorseGraph,
    SuspensionPath,
    atom_set_components,
    audit_suspension_grid_endpoints,
    compute_suspension_grid_relation,
    compute_suspension_morse_graph,
    piece_evaluation_offsets,
    relation_image_connectivity,
)
from .suspension_grid_conley import (
    SuspensionGridConleyResult,
    compute_suspension_grid_conley_index,
    piece_rectangles,
    suspension_grid_gluing,
)
from .suspension_grid_plot import suspension_grid_morse_plot_data
# Visualization
from .plot_utils import (
    HybridPlotter,
    plot_morse_graph_viz,
    plot_morse_sets_3d,
    plot_morse_sets_on_grid,
    plot_morse_sets_projections,
    visualize_box_map,
    visualize_box_map_entry,
    visualize_flow_map,
)
from .trajectory_utils import *

__all__ = [
    # Paper suspension grid Xi_n (def:suspension-grid) and its sampled map
    "DyadicBaseWindow",
    "GeneratorKey",
    "GuardResetSpec",
    "LocatedPoints",
    "SuspensionGrid",
    "SuspensionGridCheck",
    "UnsupportedSuspensionGridError",
    "build_suspension_grid",
    "check_suspension_grid",
    "EndpointBatch",
    "SuspensionFlow",
    "SuspensionGridProblem",
    "SuspensionGridRelation",
    "SuspensionMorseGraph",
    "SuspensionPath",
    "atom_set_components",
    "audit_suspension_grid_endpoints",
    "compute_suspension_grid_relation",
    "compute_suspension_morse_graph",
    "piece_evaluation_offsets",
    "relation_image_connectivity",
    "SuspensionGridConleyResult",
    "compute_suspension_grid_conley_index",
    "piece_rectangles",
    "suspension_grid_gluing",
    "suspension_grid_morse_plot_data",
    # Core classes
    "HybridSystem",
    "HybridTrajectory",
    "TrajectorySegment",
    "HybridTime",
    "HybridTimeInterval",
    "HybridBoxMap",
    "CMGDBSuspensionBoxMap",
    "SINGLE_HANDLE_BRIDGE_ALGORITHM",
    "SINGLE_HANDLE_BRIDGE_ASSUMPTIONS",
    "SuspensionAtlasCharts",
    "SuspensionStratum",
    "SamplingFailure",
    "SingleHandleBridgeDiagnostic",
    "SingleHandleBridgeProbe",
    "SourceBoxMapDiagnostic",
    "SuspensionBoxMapDiagnostics",
    "TaggedRectangle",
    "build_cmgdb_atlas_model",
    # Grid and cubification
    "Box",
    "SquareBox",
    "Grid",
    "DatasetCubifier",
    "evaluate_grid",
    "GridEvaluationResult",
    # Graph analysis
    "create_morse_graph",
    # MultiGrid framework
    "MultiGrid",
    "MultiGridBoxMap",
    # Unit-handle suspension sampling and graph diagnostics
    "BaseSuspensionSample",
    "HandleSuspensionSample",
    "SuspensionSample",
    "AugmentedCell",
    "BaseCell",
    "PhaseCell",
    "sample_suspension_trajectory",
    "simulate_suspension_endpoint",
    "locate_augmented_cells",
    "build_augmented_outer_graph",
    "crossing_completed_state",
    "simulate_crossing_completed_state",
    "collapse_phase_paths",
    "RecurrentMorseCollapseDiagnostic",
    "PhaseOnlyRecurrentComponentError",
    "diagnose_recurrent_morse_collapse",
    "assert_recurrent_morse_equivalence",
    # Reset-glued suspension cell complexes and fixed-time carriers
    "FiniteCellComplex",
    "CubicalCell",
    "CubicalGridComplex",
    "CubicalHyperplaneAttachmentAudit",
    "build_cubical_grid_complex",
    "audit_cubical_hyperplane_attachment",
    "CellularAttachmentMap",
    "CellularMapBetweenComplexes",
    "CrossComplexAcyclicCarrier",
    "DoubleMappingCylinderComplex",
    "DoubleMappingCylinderHandle",
    "CellularResetMap",
    "ResetHandle",
    "SampledSuspensionCellAdapter",
    "SparseCubicalGridComplex",
    "SuspensionBaseCell",
    "GuardPrismCell",
    "PhaseSliceCell",
    "PhaseCellRegistry",
    "SuspensionCellComplex",
    "RelativeCellPair",
    "RelativeHomologyBasis",
    "FixedTimeCellRelation",
    "FixedTimeCarrier",
    "CellularChainMap",
    "CMGDBCellRelationPayload",
    "CMGDBRelativeHomologyPayload",
    # Actual Atlas quotient nerves and physical Conley preparation
    "AffineBoundaryEmbedding2D",
    "AtlasGoodCoverError",
    "AtlasMappingCylinderConleyPreparation",
    "AtlasMappingCylinderRegistry",
    "AtlasMappingCylinderRelativePair",
    "AtlasMappingCylinderTopCell",
    "AtlasNerveSimplex",
    "AtlasPhysicalConleyPreparation2D",
    "AtlasQuotientNerveComplex2D",
    "AtlasRectangleCell2D",
    "AtlasRelativeIndexPair2D",
    "AtlasResetGluing2D",
    "AtlasSeamSubcomplexAudit2D",
    "PhysicalConleyCertificationError",
    "QuotientIntersectionAudit2D",
    "QuotientRectangleRepresentative2D",
    "RawAtlasCellCover2D",
    "atlas_cells_from_morse_graph",
    "atlas_cells_from_phase_space",
    "prepare_atlas_physical_conley_2d",
    "prepare_atlas_mapping_cylinder_conley",
    "prepare_atlas_relation_conley_2d",
    # Full SCC reconstruction from base macro graphs
    "VirtualPhaseNode",
    "PhasePathDescriptor",
    "PhaseGadgetDescriptor",
    "PhaseDescriptor",
    "FullSCCReconstruction",
    "build_base_macro_graph",
    "reconstruct_from_base_descriptors",
    "reconstruct_full_scc_condensation",
    "FixedTimeSuspensionGridResult",
    "GridResetHandle",
    "GridSuspensionIngredients",
    "SuspensionCemeteryCell",
    "compute_fixed_time_suspension_grid",
    # Falsification and quotient-connectivity diagnostics
    "AuditedCell",
    "RelationAuditFailure",
    "EndpointProbe",
    "EndpointCoverageWitness",
    "EndpointEvaluationFailure",
    "EndpointCoverageAudit",
    "audit_endpoint_probes",
    "audit_dense_base_endpoints",
    "AugmentedQuotientIncidence",
    "CellSetConnectivity",
    "RelationConnectivityAudit",
    "audit_relation_image_connectivity",
    "audit_cell_sets_connectivity",
    # Visualization
    "HybridPlotter",
    "visualize_flow_map",
    "visualize_box_map",
    "visualize_box_map_entry",
    "plot_morse_graph_viz",
    "plot_morse_sets_on_grid",
    "plot_morse_sets_3d",
    "plot_morse_sets_projections",
    "CMGDB_MORSE_PALETTE",
    "SCIENTIFIC_MORSE_PALETTE",
    "HybridMorseComponent",
    "HybridMorsePlot",
    "hybrid_morse_components",
    "hybrid_morse_hasse",
    "PlotHybridMorseSets",
    "plot_hybrid_morse_sets",
    "save_hybrid_morse_figure",
    "ATLAS_MORSE_PLOT_SCHEMA",
    "PHYSICAL_CONLEY_FINITE_RELATION_AUDIT_SCHEMA",
    "AtlasFiniteRelationIndexAnnotations",
    "AtlasMorseBox",
    "AtlasMorseNode",
    "AtlasMorsePlotData",
    "AtlasHybridMorseComponent",
    "AtlasHybridMorsePlot",
    "extract_atlas_morse_plot_data",
    "atlas_morse_plot_data_payload",
    "save_atlas_morse_plot_data",
    "load_atlas_morse_plot_data",
    "load_atlas_finite_relation_index_annotations",
    "atlas_morse_components",
    "atlas_morse_hasse",
    "plot_atlas_hybrid_morse_sets",
]
