"""Suspension grids of the manuscript (Definition ``def:suspension-grid``).

This module constructs the grid ``Xi_n`` on a computational window of the
hybrid suspension ``Sigma X`` exactly as the manuscript defines it, for a
two-dimensional base with a one-dimensional guard:

* the phase grids ``I_{n,k} = [k a_n, (k+1) a_n]`` with ``a_n = 2^{-n-2}``;
* a contracting cofiltration ``(X_j)`` of base grids obtained from one ambient
  rectangle by repeated halving (level ``j`` has ``2^{j + level_offset}``
  cells per axis), traced on a window ``R`` that is a union of finest cells;
* the generators ``K_j(mu)`` (regularized ``E_j(mu)``) and ``Q_j(mu, k)`` for
  every level ``j <= n``, so that ``Xi_n = Xi_{n-1} ^ Xi_n(X_n)`` is the
  common refinement used by the manuscript; and
* the atoms of the Boolean algebra generated by these sets.

Every generator is a finite union of *elementary pieces*:

* base pieces, the finest base cells ``|mu|`` of level ``n``; and
* handle pieces ``pi(J x I_{n,k})``, where ``J`` runs over the common
  refinement of the guard intervals ``|mu| cap G`` and ``r^{-1}(|mu|)``
  (all levels ``j <= n``; the level-``n`` breakpoints contain those of the
  coarser levels) and ``I_{n,k}`` over the phase grid of level ``n``.

A piece lies in ``K_j(nu)``, ``Q_j(nu, k)`` or neither; its *signature* is the
set of generators containing it.  Since every piece is a regular closed set
with nonempty interior and the pieces form a grid on the window, the atoms of
the generated Boolean algebra are exactly the nonempty unions of pieces with a
common signature.  Degenerate parts of ``E_j(mu)`` (for example a cell that
meets the guard only at a corner) have empty interior and are removed by the
regularization; at the piece level they simply contain no piece.

The window is ``D = Sigma(R) = iota(R) cup pi((G cap R) x [0,1])``.  The
module requires ``r(G cap R) subset R`` so that every top collar lies over a
base cell of ``R``; this holds for all examples of the manuscript.

The guard is described by a parametrization ``u -> gamma(u)`` of ``G cap R``
over an interval and the reset by ``u -> r(gamma(u))``.  Each coordinate of
both maps must be constant or strictly monotone on the interval; the grid
crossings are then computed exactly (by bisection) and a clear error is
raised for unsupported non-monotone data.
"""

from __future__ import annotations

from collections.abc import Callable, Sequence
from dataclasses import dataclass, field
from typing import Any

import numpy as np
import numpy.typing as npt
from scipy import sparse


FloatArray = npt.NDArray[np.float64]
IntArray = npt.NDArray[np.int64]

BASE_PIECE = 0
HANDLE_PIECE = 1


class UnsupportedSuspensionGridError(NotImplementedError):
    """Raised for guard/reset data outside the implemented setting."""


# ---------------------------------------------------------------------------
# Input specification
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class DyadicBaseWindow:
    """Dyadic base grids ``X_j`` on a window ``R`` inside an ambient rectangle.

    Level ``j`` subdivides ``ambient_bounds`` into ``2**(j + level_offset)``
    cells per axis.  ``region`` receives the centers of the finest cells as an
    ``(N, 2)`` array and returns the Boolean mask of cells contained in ``R``;
    ``None`` means ``R`` is the ambient rectangle.  ``R`` must be a union of
    finest cells, and the level-``j`` cells are the nonempty traces of the
    ambient level-``j`` cells on ``R``.
    """

    ambient_bounds: tuple[tuple[float, float], tuple[float, float]]
    level_offset: int = 0
    region: Callable[[FloatArray], npt.NDArray[np.bool_]] | None = None
    name: str = ""

    def __post_init__(self) -> None:
        bounds = tuple(
            (float(interval[0]), float(interval[1])) for interval in self.ambient_bounds
        )
        if len(bounds) != 2:
            raise UnsupportedSuspensionGridError(
                "the suspension grid is implemented for a two-dimensional base"
            )
        for lower, upper in bounds:
            if not (np.isfinite(lower) and np.isfinite(upper) and lower < upper):
                raise ValueError("ambient bounds must be finite nondegenerate intervals")
        object.__setattr__(self, "ambient_bounds", bounds)
        if isinstance(self.level_offset, bool) or int(self.level_offset) < 0:
            raise ValueError("level_offset must be a nonnegative integer")
        object.__setattr__(self, "level_offset", int(self.level_offset))

    def cells_per_axis(self, level: int) -> int:
        return 2 ** (int(level) + self.level_offset)

    def contains(
        self,
        points: npt.ArrayLike,
        level: int,
        *,
        tolerance: float = 1.0e-9,
    ) -> npt.NDArray[np.bool_]:
        """Closed membership in ``R`` (a union of level-``level`` cells)."""

        values = np.atleast_2d(np.asarray(points, dtype=np.float64))
        m = self.cells_per_axis(level)
        lower = np.array([self.ambient_bounds[0][0], self.ambient_bounds[1][0]])
        upper = np.array([self.ambient_bounds[0][1], self.ambient_bounds[1][1]])
        widths = (upper - lower) / m
        fractional = (values - lower) / widths
        finite = np.all(np.isfinite(fractional), axis=1)
        inside_box = finite & np.all(
            (fractional >= -tolerance) & (fractional <= m + tolerance), axis=1
        )
        if self.region is None:
            return inside_box
        result = np.zeros(values.shape[0], dtype=bool)
        for shift_x in (0.0, -tolerance, tolerance):
            for shift_y in (0.0, -tolerance, tolerance):
                cells = np.floor(fractional + np.array([shift_x, shift_y]))
                cells = np.clip(cells, 0, m - 1)
                centers = lower + (cells + 0.5) * widths
                candidate = inside_box & ~result
                if np.any(candidate):
                    inside = np.asarray(self.region(centers[candidate]), dtype=bool)
                    result[np.flatnonzero(candidate)[inside]] = True
        return result


@dataclass(frozen=True)
class GuardResetSpec:
    """Parametrized guard ``G cap R`` and reset ``r`` on it.

    ``guard_point(u)`` maps an array of guard coordinates in ``u_bounds`` to
    the ``(N, 2)`` base points ``gamma(u)``.  ``guard_coordinate(x)`` is the
    inverse chart on the whole guard ``G`` (it is also applied to guard points
    outside ``R`` to decide whether a handle endpoint lies in the window).
    ``reset_point(u)`` returns ``r(gamma(u))``.
    """

    u_bounds: tuple[float, float]
    guard_point: Callable[[FloatArray], FloatArray]
    guard_coordinate: Callable[[FloatArray], FloatArray]
    reset_point: Callable[[FloatArray], FloatArray]
    name: str = ""

    def __post_init__(self) -> None:
        lower, upper = (float(value) for value in self.u_bounds)
        if not (np.isfinite(lower) and np.isfinite(upper) and lower < upper):
            raise ValueError("u_bounds must be a finite nondegenerate interval")
        object.__setattr__(self, "u_bounds", (lower, upper))

    def gamma(self, u: npt.ArrayLike) -> FloatArray:
        values = np.atleast_1d(np.asarray(u, dtype=np.float64))
        points = np.asarray(self.guard_point(values), dtype=np.float64)
        return points.reshape(values.shape[0], 2)

    def reset(self, u: npt.ArrayLike) -> FloatArray:
        values = np.atleast_1d(np.asarray(u, dtype=np.float64))
        points = np.asarray(self.reset_point(values), dtype=np.float64)
        return points.reshape(values.shape[0], 2)

    def coordinate(self, x: npt.ArrayLike) -> FloatArray:
        points = np.atleast_2d(np.asarray(x, dtype=np.float64))
        return np.asarray(self.guard_coordinate(points), dtype=np.float64).reshape(-1)


# ---------------------------------------------------------------------------
# Monotone curve utilities
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class _CurveProfile:
    """Per-coordinate monotonicity classification of a parametrized curve."""

    kinds: tuple[str, str]  # "constant", "increasing", "decreasing"
    straight: bool


def _curve_profile(
    curve: Callable[[FloatArray], FloatArray],
    u_bounds: tuple[float, float],
    *,
    scale: tuple[float, float],
    name: str,
    samples: int = 4097,
) -> _CurveProfile:
    u = np.linspace(u_bounds[0], u_bounds[1], samples)
    points = curve(u)
    if points.shape != (samples, 2) or not np.all(np.isfinite(points)):
        raise ValueError(f"{name} must return finite (N, 2) points")
    kinds: list[str] = []
    for axis in range(2):
        values = points[:, axis]
        tolerance = 1.0e-12 * max(scale[axis], float(np.max(np.abs(values))), 1.0)
        span = float(np.max(values) - np.min(values))
        if span <= tolerance:
            kinds.append("constant")
            continue
        steps = np.diff(values)
        if np.all(steps > 0.0):
            kinds.append("increasing")
        elif np.all(steps < 0.0):
            kinds.append("decreasing")
        else:
            raise UnsupportedSuspensionGridError(
                f"coordinate {axis} of {name} is neither constant nor strictly "
                "monotone on the guard interval; the grid crossings of such a "
                "curve are not implemented"
            )
    chord = points[-1] - points[0]
    length = float(np.hypot(*chord))
    if length == 0.0:
        raise UnsupportedSuspensionGridError(f"{name} is constant on the guard interval")
    normal = np.array((-chord[1], chord[0])) / length
    deviation = float(np.max(np.abs((points - points[0]) @ normal)))
    straight = deviation <= 1.0e-10 * max(length, 1.0)
    return _CurveProfile(kinds=(kinds[0], kinds[1]), straight=straight)


def _bisect_level(
    curve: Callable[[FloatArray], FloatArray],
    axis: int,
    increasing: bool,
    targets: FloatArray,
    u_bounds: tuple[float, float],
    iterations: int = 80,
) -> FloatArray:
    """Solve ``curve(u)[axis] = target`` for a strictly monotone coordinate."""

    lower = np.full(targets.shape, u_bounds[0], dtype=np.float64)
    upper = np.full(targets.shape, u_bounds[1], dtype=np.float64)
    for _ in range(iterations):
        middle = 0.5 * (lower + upper)
        values = curve(middle)[:, axis]
        below = values < targets if increasing else values > targets
        lower = np.where(below, middle, lower)
        upper = np.where(below, upper, middle)
        if np.all(upper - lower <= 4.0 * np.finfo(float).eps * np.maximum(1.0, np.abs(upper))):
            break
    return 0.5 * (lower + upper)


def _curve_grid_crossings(
    curve: Callable[[FloatArray], FloatArray],
    profile: _CurveProfile,
    u_bounds: tuple[float, float],
    grid_lines: Sequence[FloatArray],
) -> FloatArray:
    """Parameters at which a monotone curve crosses finest-grid lines."""

    endpoints = curve(np.asarray(u_bounds, dtype=np.float64))
    crossings: list[FloatArray] = []
    for axis in range(2):
        kind = profile.kinds[axis]
        if kind == "constant":
            continue
        low = min(endpoints[0, axis], endpoints[1, axis])
        high = max(endpoints[0, axis], endpoints[1, axis])
        lines = np.asarray(grid_lines[axis], dtype=np.float64)
        inside = lines[(lines > low) & (lines < high)]
        if inside.size:
            crossings.append(
                _bisect_level(curve, axis, kind == "increasing", inside, u_bounds)
            )
    if not crossings:
        return np.zeros(0, dtype=np.float64)
    return np.concatenate(crossings)


def _invert_curve(
    curve: Callable[[FloatArray], FloatArray],
    profile: _CurveProfile,
    u_bounds: tuple[float, float],
    points: FloatArray,
) -> FloatArray:
    """Invert a monotone curve on the points; ``nan`` where ill-defined."""

    ends = curve(np.asarray(u_bounds, dtype=np.float64))
    spans = np.abs(ends[1] - ends[0])
    candidates = [axis for axis in range(2) if profile.kinds[axis] != "constant"]
    axis = max(candidates, key=lambda index: spans[index])
    increasing = profile.kinds[axis] == "increasing"
    targets = np.clip(
        points[:, axis],
        min(ends[0, axis], ends[1, axis]),
        max(ends[0, axis], ends[1, axis]),
    )
    return _bisect_level(curve, axis, increasing, targets, u_bounds)


def _segments_intersect(
    first: FloatArray,
    second: FloatArray,
    tolerance: float,
) -> bool:
    """Closed polyline intersection test with an absolute tolerance."""

    for a0, a1 in zip(first[:-1], first[1:]):
        for b0, b1 in zip(second[:-1], second[1:]):
            if _segment_pair_intersect(a0, a1, b0, b1, tolerance):
                return True
    return False


def _segment_pair_intersect(
    p0: FloatArray, p1: FloatArray, q0: FloatArray, q1: FloatArray, tol: float
) -> bool:
    def point_segment_distance(point: FloatArray, a: FloatArray, b: FloatArray) -> float:
        direction = b - a
        denominator = float(direction @ direction)
        if denominator == 0.0:
            return float(np.hypot(*(point - a)))
        t = float(np.clip((point - a) @ direction / denominator, 0.0, 1.0))
        return float(np.hypot(*(point - (a + t * direction))))

    def cross(a: FloatArray, b: FloatArray) -> float:
        return float(a[0] * b[1] - a[1] * b[0])

    r = p1 - p0
    s = q1 - q0
    denominator = cross(r, s)
    if denominator != 0.0:
        t = cross(q0 - p0, s) / denominator
        v = cross(q0 - p0, r) / denominator
        if -1.0e-12 <= t <= 1.0 + 1.0e-12 and -1.0e-12 <= v <= 1.0 + 1.0e-12:
            return True
    return min(
        point_segment_distance(p0, q0, q1),
        point_segment_distance(p1, q0, q1),
        point_segment_distance(q0, p0, p1),
        point_segment_distance(q1, p0, p1),
    ) <= tol


# ---------------------------------------------------------------------------
# The grid
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class GeneratorKey:
    """A generator ``K_j(nu)`` (``kind='K'``) or ``Q_j(nu, k)`` (``'Q'``).

    ``cell`` is the ambient level-``level`` address ``(i, k)`` of ``nu``.
    """

    kind: str
    level: int
    cell: tuple[int, int]
    phase: int = -1


@dataclass(frozen=True)
class LocatedPoints:
    """Closed-cell location of points: ``(point index, piece id)`` incidences."""

    point_index: IntArray
    piece: IntArray

    def pieces_of(self, index: int) -> IntArray:
        return self.piece[self.point_index == index]


@dataclass
class SuspensionGrid:
    """The suspension grid ``Xi_n`` on the window ``D = Sigma(R)``.

    Piece ids ``0 .. n_base-1`` are the finest base cells; piece
    ``n_base + J * n_phase + k`` is the handle piece ``pi(J x I_{n,k})``.
    Atoms (the elements of ``Xi_n``) are indexed ``0 .. n_atoms-1``.
    """

    window: DyadicBaseWindow
    guard: GuardResetSpec
    level: int
    cells_per_axis: int
    cell_widths: FloatArray
    base_cell_index: IntArray  # (m, m) -> base piece id or -1
    base_addresses: IntArray  # (n_base, 2) ambient addresses (ix, iy)
    u_edges: FloatArray  # guard partition breakpoints, length n_guard + 1
    n_phase: int
    guard_bottom_cells: tuple[IntArray, ...]  # finest cells containing gamma(J)
    guard_top_cells: tuple[IntArray, ...]  # finest cells containing r(gamma(J))
    n_generators: int  # generators K_j(mu), Q_j(mu, k) with a piece, j <= n
    atom_of_piece: IntArray
    atom_offsets: IntArray  # CSR offsets into atom_pieces
    atom_pieces: IntArray
    d_map: IntArray  # d_n: base piece (= finest base cell) -> atom
    piece_adjacency: sparse.csr_matrix
    atom_adjacency: sparse.csr_matrix
    guard_profile: _CurveProfile
    reset_profile: _CurveProfile
    location_tolerance: float
    metadata: dict[str, Any] = field(default_factory=dict)
    _reference: tuple[Any, ...] | None = field(default=None, repr=False, compare=False)

    # -- generators -------------------------------------------------------------
    @property
    def signatures(self) -> tuple[tuple[int, ...], ...]:
        """Sorted generator ids of every piece (computed on first use)."""

        return self._reference_signatures()[0]

    @property
    def generators(self) -> tuple[GeneratorKey, ...]:
        """Generator keys in the order of their ids (computed on first use)."""

        return self._reference_signatures()[1]

    def _reference_signatures(self) -> tuple[Any, ...]:
        if self._reference is None:
            self._reference = reference_signatures(self)
        return self._reference

    # -- sizes ------------------------------------------------------------
    @property
    def a_n(self) -> float:
        return 1.0 / self.n_phase

    @property
    def n_base(self) -> int:
        return int(self.base_addresses.shape[0])

    @property
    def n_guard(self) -> int:
        return int(self.u_edges.shape[0] - 1)

    @property
    def n_handle(self) -> int:
        return self.n_guard * self.n_phase

    @property
    def n_pieces(self) -> int:
        return self.n_base + self.n_handle

    @property
    def n_atoms(self) -> int:
        return int(self.atom_offsets.shape[0] - 1)

    def atom(self, index: int) -> IntArray:
        return self.atom_pieces[self.atom_offsets[index] : self.atom_offsets[index + 1]]

    # -- piece geometry ----------------------------------------------------
    def piece_kind(self, piece: npt.ArrayLike) -> IntArray:
        values = np.asarray(piece, dtype=np.int64)
        return np.where(values < self.n_base, BASE_PIECE, HANDLE_PIECE)

    def handle_piece(self, guard_index: npt.ArrayLike, phase: npt.ArrayLike) -> IntArray:
        return (
            self.n_base
            + np.asarray(guard_index, dtype=np.int64) * self.n_phase
            + np.asarray(phase, dtype=np.int64)
        )

    def handle_indices(self, piece: npt.ArrayLike) -> tuple[IntArray, IntArray]:
        values = np.asarray(piece, dtype=np.int64) - self.n_base
        return values // self.n_phase, values % self.n_phase

    def base_bounds(self, piece: npt.ArrayLike) -> FloatArray:
        """``(N, 4)`` rectangles ``(x0, y0, x1, y1)`` of base pieces."""

        addresses = self.base_addresses[np.asarray(piece, dtype=np.int64)]
        lower = self._ambient_lower + addresses * self.cell_widths
        return np.concatenate((lower, lower + self.cell_widths), axis=-1)

    def handle_bounds(self, piece: npt.ArrayLike) -> FloatArray:
        """``(N, 4)`` rectangles ``(u0, s0, u1, s1)`` of handle pieces."""

        guard_index, phase = self.handle_indices(piece)
        return np.stack(
            (
                self.u_edges[guard_index],
                phase / self.n_phase,
                self.u_edges[guard_index + 1],
                (phase + 1) / self.n_phase,
            ),
            axis=-1,
        )

    @property
    def _ambient_lower(self) -> FloatArray:
        return np.array(
            [self.window.ambient_bounds[0][0], self.window.ambient_bounds[1][0]]
        )

    # -- d_n and the base readout -----------------------------------------
    def d(self, base_cells: npt.ArrayLike) -> IntArray:
        """The injection ``d_n : X_n -> Xi_n`` of ``prop:suspension-grid``."""

        return self.d_map[np.asarray(base_cells, dtype=np.int64)]

    def base_readout(self, atoms: npt.ArrayLike) -> IntArray:
        """``d_n^{-1}(U)``: base cells ``mu`` with ``d_n(mu) in U``.

        By ``prop:finite-grid-preimage`` its union is the regularized preimage
        ``rho_n(|U|)``.
        """

        selected = np.zeros(self.n_atoms, dtype=bool)
        selected[np.asarray(atoms, dtype=np.int64)] = True
        return np.flatnonzero(selected[self.d_map])

    # -- point location -----------------------------------------------------
    def _axis_candidates(self, values: FloatArray, axis: int) -> tuple[IntArray, IntArray]:
        """Closed cell indices along one axis: ``(point index, cell index)``."""

        lower = self.window.ambient_bounds[axis][0]
        width = self.cell_widths[axis]
        fractional = (values - lower) / width
        nearest = np.rint(fractional)
        on_line = np.abs(fractional - nearest) <= self.location_tolerance
        floor = np.floor(fractional).astype(np.int64)
        rows = [np.arange(values.shape[0])]
        cells = [np.where(on_line, nearest.astype(np.int64), floor)]
        rows.append(np.flatnonzero(on_line))
        cells.append(nearest[on_line].astype(np.int64) - 1)
        row = np.concatenate(rows)
        cell = np.concatenate(cells)
        keep = (cell >= 0) & (cell < self.cells_per_axis) & np.isfinite(values[row])
        return row[keep], cell[keep]

    def locate_base_cells(self, points: npt.ArrayLike) -> LocatedPoints:
        """Finest base cells whose closed rectangle contains each point."""

        values = np.atleast_2d(np.asarray(points, dtype=np.float64))
        rows_x, cells_x = self._axis_candidates(values[:, 0], 0)
        rows_y, cells_y = self._axis_candidates(values[:, 1], 1)
        if rows_x.size == 0 or rows_y.size == 0:
            return LocatedPoints(np.zeros(0, np.int64), np.zeros(0, np.int64))
        # Join the per-axis candidates on the point index (at most 2 x 2).
        order_x = np.argsort(rows_x, kind="stable")
        rows_x, cells_x = rows_x[order_x], cells_x[order_x]
        order_y = np.argsort(rows_y, kind="stable")
        rows_y, cells_y = rows_y[order_y], cells_y[order_y]
        point_list: list[IntArray] = []
        piece_list: list[IntArray] = []
        for shift_x in range(2):
            for shift_y in range(2):
                # k-th candidate of each axis for the same point.
                sel_x = _kth_per_group(rows_x, shift_x)
                sel_y = _kth_per_group(rows_y, shift_y)
                common, ix, iy = np.intersect1d(
                    rows_x[sel_x], rows_y[sel_y], return_indices=True
                )
                if common.size == 0:
                    continue
                pieces = self.base_cell_index[
                    cells_x[sel_x][ix], cells_y[sel_y][iy]
                ]
                keep = pieces >= 0
                point_list.append(common[keep])
                piece_list.append(pieces[keep])
        if not point_list:
            return LocatedPoints(np.zeros(0, np.int64), np.zeros(0, np.int64))
        return LocatedPoints(np.concatenate(point_list), np.concatenate(piece_list))

    def locate_guard_intervals(self, u: npt.ArrayLike) -> tuple[IntArray, IntArray]:
        """Closed guard intervals ``J`` containing each coordinate."""

        values = np.atleast_1d(np.asarray(u, dtype=np.float64))
        scale = self.guard_scale
        tolerance = self.location_tolerance * scale
        inside = (values >= self.u_edges[0] - tolerance) & (
            values <= self.u_edges[-1] + tolerance
        )
        clipped = np.clip(values, self.u_edges[0], self.u_edges[-1])
        index = np.searchsorted(self.u_edges, clipped, side="right") - 1
        index = np.clip(index, 0, self.n_guard - 1)
        rows = [np.flatnonzero(inside)]
        cells = [index[inside]]
        near_lower = inside & (np.abs(clipped - self.u_edges[index]) <= tolerance) & (index > 0)
        rows.append(np.flatnonzero(near_lower))
        cells.append(index[near_lower] - 1)
        near_upper = (
            inside
            & (np.abs(clipped - self.u_edges[index + 1]) <= tolerance)
            & (index + 1 < self.n_guard)
        )
        rows.append(np.flatnonzero(near_upper))
        cells.append(index[near_upper] + 1)
        return np.concatenate(rows), np.concatenate(cells)

    def locate_phases(self, s: npt.ArrayLike) -> tuple[IntArray, IntArray]:
        """Closed phase intervals ``I_{n,k}`` containing each phase in ``[0,1]``."""

        values = np.atleast_1d(np.asarray(s, dtype=np.float64))
        scaled = values * self.n_phase
        nearest = np.rint(scaled)
        on_line = np.abs(scaled - nearest) <= self.location_tolerance
        index = np.where(on_line, nearest, np.floor(scaled)).astype(np.int64)
        rows = [np.arange(values.shape[0])]
        cells = [index]
        rows.append(np.flatnonzero(on_line))
        cells.append(index[on_line] - 1)
        row = np.concatenate(rows)
        cell = np.concatenate(cells)
        keep = (cell >= 0) & (cell < self.n_phase)
        return row[keep], cell[keep]

    @property
    def guard_scale(self) -> float:
        return float(max(abs(self.u_edges[-1] - self.u_edges[0]), 1.0e-300))

    def guard_membership(self, points: npt.ArrayLike) -> FloatArray:
        """Guard coordinate of base points on ``G cap R``; ``nan`` otherwise."""

        values = np.atleast_2d(np.asarray(points, dtype=np.float64))
        u = self.guard.coordinate(values)
        inside = np.isfinite(u)
        tolerance = self.location_tolerance * self.guard_scale
        inside &= (u >= self.u_edges[0] - tolerance) & (u <= self.u_edges[-1] + tolerance)
        result = np.full(values.shape[0], np.nan)
        if np.any(inside):
            clipped = np.clip(u[inside], self.u_edges[0], self.u_edges[-1])
            residual = np.max(
                np.abs(self.guard.gamma(clipped) - values[inside]) / self.cell_widths,
                axis=1,
            )
            ok = residual <= self.location_tolerance
            indices = np.flatnonzero(inside)[ok]
            result[indices] = clipped[ok]
        return result

    def reset_membership(self, points: npt.ArrayLike) -> FloatArray:
        """``u`` with ``r(gamma(u)) = x`` for base points on ``r(G cap R)``."""

        values = np.atleast_2d(np.asarray(points, dtype=np.float64))
        u = _invert_curve(
            self.guard.reset, self.reset_profile, self.guard.u_bounds, values
        )
        residual = np.max(np.abs(self.guard.reset(u) - values) / self.cell_widths, axis=1)
        return np.where(residual <= self.location_tolerance, u, np.nan)

    def locate_base_points(self, points: npt.ArrayLike) -> LocatedPoints:
        """Pieces of ``Xi_n`` whose closure contains ``iota(x)``.

        A point on ``G cap R`` also lies in the handle pieces at phase zero
        over it, and a point of ``r(G cap R)`` in the handle pieces at phase
        one over its reset preimage (the identifications ``pi(g,0)=iota(g)``
        and ``pi(g,1)=iota(r(g))``).  Points outside ``R`` are not located.
        """

        values = np.atleast_2d(np.asarray(points, dtype=np.float64))
        located = self.locate_base_cells(values)
        rows = [located.point_index]
        pieces = [located.piece]
        u_guard = self.guard_membership(values)
        on_guard = np.flatnonzero(np.isfinite(u_guard))
        if on_guard.size:
            guard_rows, guard_cells = self.locate_guard_intervals(u_guard[on_guard])
            rows.append(on_guard[guard_rows])
            pieces.append(self.handle_piece(guard_cells, 0))
        u_reset = self.reset_membership(values)
        on_reset = np.flatnonzero(np.isfinite(u_reset))
        if on_reset.size:
            reset_rows, reset_cells = self.locate_guard_intervals(u_reset[on_reset])
            rows.append(on_reset[reset_rows])
            pieces.append(self.handle_piece(reset_cells, self.n_phase - 1))
        return _unique_located(np.concatenate(rows), np.concatenate(pieces))

    def locate_handle_points(self, u: npt.ArrayLike, s: npt.ArrayLike) -> LocatedPoints:
        """Pieces whose closure contains ``pi(gamma(u), s)``.

        Coordinates outside ``G cap R`` are not located.  At ``s = 0`` and
        ``s = 1`` the base cells containing ``gamma(u)`` and ``r(gamma(u))``
        are added (the two sides of an identification).
        """

        u_values = np.atleast_1d(np.asarray(u, dtype=np.float64))
        s_values = np.atleast_1d(np.asarray(s, dtype=np.float64))
        guard_rows, guard_cells = self.locate_guard_intervals(u_values)
        phase_rows, phase_cells = self.locate_phases(s_values)
        rows: list[IntArray] = []
        pieces: list[IntArray] = []
        for first in range(3):
            sel_g = _kth_per_group_unsorted(guard_rows, first)
            for second in range(2):
                sel_p = _kth_per_group_unsorted(phase_rows, second)
                common, ig, ip = np.intersect1d(
                    guard_rows[sel_g], phase_rows[sel_p], return_indices=True
                )
                if common.size:
                    rows.append(common)
                    pieces.append(
                        self.handle_piece(guard_cells[sel_g][ig], phase_cells[sel_p][ip])
                    )
        tolerance = self.location_tolerance
        in_window = np.zeros(u_values.shape[0], dtype=bool)
        in_window[guard_rows] = True
        at_zero = np.flatnonzero(in_window & (s_values <= tolerance))
        if at_zero.size:
            located = self.locate_base_cells(
                self.guard.gamma(np.clip(u_values[at_zero], *self.guard.u_bounds))
            )
            rows.append(at_zero[located.point_index])
            pieces.append(located.piece)
        at_one = np.flatnonzero(in_window & (s_values >= 1.0 - tolerance))
        if at_one.size:
            located = self.locate_base_cells(
                self.guard.reset(np.clip(u_values[at_one], *self.guard.u_bounds))
            )
            rows.append(at_one[located.point_index])
            pieces.append(located.piece)
        if not rows:
            return LocatedPoints(np.zeros(0, np.int64), np.zeros(0, np.int64))
        return _unique_located(np.concatenate(rows), np.concatenate(pieces))

    def base_points_in_window(self, points: npt.ArrayLike) -> npt.NDArray[np.bool_]:
        values = np.atleast_2d(np.asarray(points, dtype=np.float64))
        located = self.locate_base_cells(values)
        result = np.zeros(values.shape[0], dtype=bool)
        result[located.point_index] = True
        return result

    # -- refinement ---------------------------------------------------------
    def piece_parent(self, coarse: "SuspensionGrid") -> IntArray:
        """The piece of ``coarse`` containing each piece of ``self``."""

        if coarse.level > self.level or coarse.window != self.window:
            raise ValueError("coarse grid must be a lower level of the same window")
        shift = self.level - coarse.level
        parents = np.empty(self.n_pieces, dtype=np.int64)
        base_parent = coarse.base_cell_index[
            self.base_addresses[:, 0] >> shift, self.base_addresses[:, 1] >> shift
        ]
        if np.any(base_parent < 0):
            raise AssertionError("a finer base cell has no coarser parent in R")
        parents[: self.n_base] = base_parent
        guard_index, phase = self.handle_indices(np.arange(self.n_base, self.n_pieces))
        middle = 0.5 * (self.u_edges[guard_index] + self.u_edges[guard_index + 1])
        coarse_guard = np.searchsorted(coarse.u_edges, middle, side="right") - 1
        parents[self.n_base :] = coarse.handle_piece(coarse_guard, phase >> shift)
        return parents

    def refinement_map(self, coarse: "SuspensionGrid") -> IntArray:
        """``q_{mn}``: the atom of ``coarse`` containing each atom of ``self``.

        Raises if some atom of ``self`` is not contained in a single atom of
        ``coarse`` (that is, if ``Xi_m`` fails to refine ``Xi_n``).
        """

        parent_atoms = coarse.atom_of_piece[self.piece_parent(coarse)]
        result = np.full(self.n_atoms, -1, dtype=np.int64)
        for atom in range(self.n_atoms):
            values = np.unique(parent_atoms[self.atom(atom)])
            if values.size != 1:
                raise AssertionError(
                    f"atom {atom} of level {self.level} meets {values.size} atoms of "
                    f"level {coarse.level}"
                )
            result[atom] = values[0]
        return result

    def summary(self) -> dict[str, Any]:
        d_atoms = np.zeros(self.n_atoms, dtype=bool)
        d_atoms[self.d_map] = True
        sizes = np.diff(self.atom_offsets)
        return {
            "level": self.level,
            "a_n": self.a_n,
            "base_cells_per_axis": self.cells_per_axis,
            "base_cell_widths": [float(value) for value in self.cell_widths],
            "base_pieces": self.n_base,
            "guard_intervals": self.n_guard,
            "phase_intervals": self.n_phase,
            "handle_pieces": self.n_handle,
            "pieces": self.n_pieces,
            "generators": self.n_generators,
            "atoms": self.n_atoms,
            "atoms_in_d_image": int(np.count_nonzero(d_atoms)),
            "atoms_without_base_cell": int(self.n_atoms - np.count_nonzero(d_atoms)),
            "max_pieces_per_atom": int(sizes.max()) if sizes.size else 0,
            "guard_curve_straight": self.guard_profile.straight,
            "reset_curve_straight": self.reset_profile.straight,
        }


def _kth_per_group(sorted_rows: IntArray, k: int) -> IntArray:
    """Indices of the ``k``-th entry of each run in a sorted row array."""

    if sorted_rows.size == 0:
        return np.zeros(0, dtype=np.int64)
    starts = np.r_[0, np.flatnonzero(np.diff(sorted_rows)) + 1]
    counts = np.diff(np.r_[starts, sorted_rows.size])
    keep = counts > k
    return starts[keep] + k


def _kth_per_group_unsorted(rows: IntArray, k: int) -> IntArray:
    order = np.argsort(rows, kind="stable")
    return order[_kth_per_group(rows[order], k)]


def _unique_located(rows: IntArray, pieces: IntArray) -> LocatedPoints:
    if rows.size == 0:
        return LocatedPoints(rows.astype(np.int64), pieces.astype(np.int64))
    pairs = np.unique(np.stack((rows, pieces), axis=1), axis=0)
    return LocatedPoints(pairs[:, 0].astype(np.int64), pairs[:, 1].astype(np.int64))


# ---------------------------------------------------------------------------
# Construction
# ---------------------------------------------------------------------------


def build_suspension_grid(
    window: DyadicBaseWindow,
    guard: GuardResetSpec,
    level: int,
    *,
    location_tolerance: float = 1.0e-9,
) -> SuspensionGrid:
    """Construct ``Xi_n`` for ``n = level`` (the cofiltration of the paper).

    ``Xi_n`` is generated by ``K_j(mu)`` and ``Q_j(mu, k)`` for all
    ``0 <= j <= n``, ``mu in X_j`` and ``1 <= k <= 2^{j+2} - 2``, which is the
    manuscript's recursive definition ``Xi_n = Xi_{n-1} ^ Xi_n(X_n)``.
    """

    if isinstance(level, bool) or not isinstance(level, (int, np.integer)) or level < 0:
        raise ValueError("level must be a nonnegative integer")
    level = int(level)
    m = window.cells_per_axis(level)
    lower = np.array([window.ambient_bounds[0][0], window.ambient_bounds[1][0]])
    upper = np.array([window.ambient_bounds[0][1], window.ambient_bounds[1][1]])
    widths = (upper - lower) / m

    # Finest base cells of R.
    ix, iy = np.meshgrid(np.arange(m), np.arange(m), indexing="ij")
    addresses = np.stack((ix.ravel(), iy.ravel()), axis=1).astype(np.int64)
    centers = lower + (addresses + 0.5) * widths
    if window.region is None:
        mask = np.ones(addresses.shape[0], dtype=bool)
    else:
        mask = np.asarray(window.region(centers), dtype=bool).reshape(-1)
        if mask.shape[0] != addresses.shape[0]:
            raise ValueError("region must return one Boolean per cell center")
    addresses = addresses[mask]
    if addresses.shape[0] == 0:
        raise ValueError("the window contains no finest cell")
    base_cell_index = np.full((m, m), -1, dtype=np.int64)
    base_cell_index[addresses[:, 0], addresses[:, 1]] = np.arange(addresses.shape[0])
    n_base = int(addresses.shape[0])

    # Guard and reset curve data.
    scale = (float(upper[0] - lower[0]), float(upper[1] - lower[1]))
    guard_profile = _curve_profile(guard.gamma, guard.u_bounds, scale=scale, name="guard_point")
    reset_profile = _curve_profile(guard.reset, guard.u_bounds, scale=scale, name="reset_point")
    grid_lines = [lower[axis] + np.arange(m + 1) * widths[axis] for axis in range(2)]
    breakpoints = np.concatenate(
        (
            np.asarray(guard.u_bounds, dtype=np.float64),
            _curve_grid_crossings(guard.gamma, guard_profile, guard.u_bounds, grid_lines),
            _curve_grid_crossings(guard.reset, reset_profile, guard.u_bounds, grid_lines),
        )
    )
    breakpoints = np.sort(breakpoints)
    span = guard.u_bounds[1] - guard.u_bounds[0]
    merge_tolerance = location_tolerance * span
    u_edges = [breakpoints[0]]
    for value in breakpoints[1:]:
        if value - u_edges[-1] > merge_tolerance:
            u_edges.append(value)
    u_edges_array = np.asarray(u_edges, dtype=np.float64)
    u_edges_array[0], u_edges_array[-1] = guard.u_bounds
    n_guard = int(u_edges_array.shape[0] - 1)

    grid = SuspensionGrid(
        window=window,
        guard=guard,
        level=level,
        cells_per_axis=m,
        cell_widths=widths,
        base_cell_index=base_cell_index,
        base_addresses=addresses,
        u_edges=u_edges_array,
        n_phase=2 ** (level + 2),
        guard_bottom_cells=(),
        guard_top_cells=(),
        n_generators=0,
        atom_of_piece=np.zeros(0, dtype=np.int64),
        atom_offsets=np.zeros(1, dtype=np.int64),
        atom_pieces=np.zeros(0, dtype=np.int64),
        d_map=np.zeros(0, dtype=np.int64),
        piece_adjacency=sparse.csr_matrix((0, 0)),
        atom_adjacency=sparse.csr_matrix((0, 0)),
        guard_profile=guard_profile,
        reset_profile=reset_profile,
        location_tolerance=float(location_tolerance),
    )

    # Finest cells meeting gamma(J) and r(gamma(J)) along the open interval J.
    middles = 0.5 * (u_edges_array[:-1] + u_edges_array[1:])

    def cells_at(points: FloatArray) -> list[IntArray]:
        located = grid.locate_base_cells(points)
        return [
            np.unique(located.piece[located.point_index == index])
            for index in range(points.shape[0])
        ]

    bottom_cells = cells_at(guard.gamma(middles))
    top_cells = cells_at(guard.reset(middles))
    for index in range(n_guard):
        if bottom_cells[index].size == 0:
            raise UnsupportedSuspensionGridError(
                "the guard parametrization leaves the window R at "
                f"u={middles[index]!r}; u_bounds must describe G cap R"
            )
        if top_cells[index].size == 0:
            raise UnsupportedSuspensionGridError(
                "r(G cap R) is not contained in R near "
                f"u={middles[index]!r}; the top collars would lie over cells "
                "outside the window, which this implementation does not support"
            )
    grid.guard_bottom_cells = tuple(bottom_cells)
    grid.guard_top_cells = tuple(top_cells)

    # Atoms: nonempty classes of pieces with a common signature, numbered in
    # the order of their first piece.
    atom_of_piece, n_generators = _signature_classes(
        addresses, grid.guard_bottom_cells, grid.guard_top_cells, level, grid.n_phase,
        window.level_offset,
    )
    order = np.argsort(atom_of_piece, kind="stable")
    counts = np.bincount(atom_of_piece)
    atom_offsets = np.r_[0, np.cumsum(counts)].astype(np.int64)

    grid.n_generators = int(n_generators)
    grid.atom_of_piece = atom_of_piece
    grid.atom_offsets = atom_offsets
    grid.atom_pieces = order.astype(np.int64)
    grid.d_map = atom_of_piece[:n_base].copy()

    # Closed-set incidence of pieces in the suspension quotient.
    grid.piece_adjacency = _piece_adjacency(grid)
    membership = sparse.csr_matrix(
        (np.ones(grid.n_pieces), (np.arange(grid.n_pieces), atom_of_piece)),
        shape=(grid.n_pieces, grid.n_atoms),
    )
    atom_adjacency = (membership.T @ grid.piece_adjacency @ membership).tocsr()
    atom_adjacency.data[:] = 1.0
    grid.atom_adjacency = atom_adjacency
    grid.metadata = {
        "construction": "paper suspension grid Xi_n (def:suspension-grid), levels 0..n",
        "window": window.name,
        "guard": guard.name,
    }
    return grid


def _last_top_levels(level: int, n_phase: int) -> IntArray:
    """For each phase ``k``: the largest ``j`` with ``k >> (n-j) = 2^{j+2}-1``, or ``-1``.

    The levels ``j`` at which the phase piece ``k`` lies in a top collar
    ``[1 - a_j, 1]`` form the initial segment ``0, ..., J(k)``.
    """

    phases = np.arange(n_phase, dtype=np.int64)
    result = np.full(n_phase, -1, dtype=np.int64)
    for j in range(level + 1):
        result[(phases >> (level - j)) == 2 ** (j + 2) - 1] = j
    return result


def _padded_rows(rows: Sequence[IntArray], width: int) -> IntArray:
    result = np.full((len(rows), width), -1, dtype=np.int64)
    for index, values in enumerate(rows):
        result[index, : values.size] = values
    return result


def _signature_classes(
    addresses: IntArray,
    bottom_cells: Sequence[IntArray],
    top_cells: Sequence[IntArray],
    level: int,
    n_phase: int,
    level_offset: int,
) -> tuple[IntArray, int]:
    """Atoms of the pieces (numbered by first piece) and the number of generators.

    The generator signature of a piece (the set of ``K_j(nu)`` and
    ``Q_j(nu, k)`` containing it) is determined by a short key:

    * a base piece ``mu`` lies in ``K_j(mu_j)`` for its ancestors ``mu_j``,
      and in no ``Q``: key ``K{mu}``;
    * a handle piece over ``J`` at phase ``0`` lies in ``K_j`` of the
      level-``j`` cells meeting ``gamma(J)`` for every ``j``: key ``K B_n(J)``
      with ``B_n(J)`` the finest cells meeting ``gamma(J)``;
    * at the last phase: key ``K T_n(J)`` with ``T_n(J)`` the finest cells
      meeting ``r(gamma(J))``;
    * at a middle phase ``k``: it lies in ``Q_n(nu, k)`` for ``nu`` in
      ``B_n(J)``, in ``K_j`` or ``Q_j`` of the ancestors of ``B_n(J)`` at the
      levels where ``k`` is a bottom or middle phase, and in ``K_j`` of the
      level-``j`` cells of ``T_n(J)`` at the levels ``j <= J(k)`` where it is
      a top phase (:func:`_last_top_levels`): key ``(k, B_n(J), J(k),
      T_{J(k)}(J))``.

    A ``K``-only signature is determined by its finest-level generators,
    which are ``K_n`` of the given cells, so two ``K``-only keys give the same
    signature exactly when their cell sets agree; a middle key contains
    ``Q_n(., k)`` and so never equals a ``K``-only one.  Base pieces are the
    first pieces and have distinct signatures, so the atom of base piece
    ``mu`` is ``mu``; a handle piece with key ``K{mu}`` joins that atom.  This
    reproduces the first-occurrence numbering of the signature classes, which
    :func:`reference_signatures` computes from the generator sets
    themselves (the tests compare the two).
    """

    n_base = int(addresses.shape[0])
    n_guard = len(bottom_cells)
    width = max(
        1,
        max((values.size for values in bottom_cells), default=0),
        max((values.size for values in top_cells), default=0),
    )
    bottom = _padded_rows([np.asarray(values, dtype=np.int64) for values in bottom_cells], width)
    top = _padded_rows([np.asarray(values, dtype=np.int64) for values in top_cells], width)
    # Level-j cells of T_n(J), encoded ix * 2^(j + offset) + iy, per level.
    top_by_level = np.full((level + 1, n_guard, width), -1, dtype=np.int64)
    for j in range(level + 1):
        side = 2 ** (j + level_offset)
        rows = []
        for values in top_cells:
            coarse = addresses[np.asarray(values, dtype=np.int64)] >> (level - j)
            rows.append(np.unique(coarse[:, 0] * side + coarse[:, 1]))
        top_by_level[j] = _padded_rows(rows, width)

    # Keys (class, phase, B or K set, J(k), T_J set) of the handle pieces.
    top_level = _last_top_levels(level, n_phase)
    columns = 3 + 2 * width
    keys = np.full((n_guard, n_phase, columns), -1, dtype=np.int64)
    keys[:, :, 0] = 1
    keys[:, :, 1] = np.arange(n_phase, dtype=np.int64)[None, :]
    keys[:, :, 2 : 2 + width] = bottom[:, None, :]
    keys[:, :, 2 + width] = top_level[None, :]
    has_top = np.flatnonzero(top_level >= 0)
    keys[:, has_top, 3 + width :] = top_by_level[top_level[has_top]].transpose(1, 0, 2)
    keys[:, 0, :] = -1
    keys[:, 0, 0] = 0
    keys[:, 0, 2 : 2 + width] = bottom
    keys[:, n_phase - 1, :] = -1
    keys[:, n_phase - 1, 0] = 0
    keys[:, n_phase - 1, 2 : 2 + width] = top
    keys = keys.reshape(n_guard * n_phase, columns)

    atom_of_piece = np.empty(n_base + keys.shape[0], dtype=np.int64)
    atom_of_piece[:n_base] = np.arange(n_base, dtype=np.int64)
    if keys.shape[0]:
        _unique, first, inverse = np.unique(
            keys, axis=0, return_index=True, return_inverse=True
        )
        inverse = inverse.reshape(-1)
        unique_keys = keys[first]
        # A K-only key with one cell (column 3 is the second cell, or J(k) = -1
        # when the sets have one column) is the key of a base piece.
        joins_base = (unique_keys[:, 0] == 0) & (unique_keys[:, 3] == -1)
        atom_of_class = np.empty(first.size, dtype=np.int64)
        atom_of_class[joins_base] = unique_keys[joins_base, 2]
        new = np.flatnonzero(~joins_base)
        rank = np.empty(new.size, dtype=np.int64)
        rank[np.argsort(first[new], kind="stable")] = np.arange(new.size)
        atom_of_class[new] = n_base + rank
        atom_of_piece[n_base:] = atom_of_class[inverse]

    # Generators: K_j(nu) for the level-j ancestors nu of the cells of R, and
    # Q_j(nu, c) for the level-j cells nu meeting the guard and the
    # 2^{j+2} - 2 middle phases c of level j.
    bottom_all = np.unique(np.concatenate([np.asarray(v, np.int64) for v in bottom_cells]))
    n_generators = 0
    for j in range(level + 1):
        side = 2 ** (j + level_offset)
        coarse = addresses >> (level - j)
        n_generators += int(np.unique(coarse[:, 0] * side + coarse[:, 1]).size)
        coarse = addresses[bottom_all] >> (level - j)
        n_generators += int(np.unique(coarse[:, 0] * side + coarse[:, 1]).size) * (
            2 ** (j + 2) - 2
        )
    return atom_of_piece, n_generators


def reference_signatures(
    grid: SuspensionGrid,
) -> tuple[tuple[tuple[int, ...], ...], tuple[GeneratorKey, ...], IntArray]:
    """Generator signatures of the pieces, enumerated generator by generator.

    Returns ``(signatures, generators, atom_of_piece)``: the sorted generator
    ids of every piece, the generator keys in the order of their ids, and the
    classes of equal signatures numbered by first piece.  This is the direct
    transcription of ``def:suspension-grid``;
    :func:`build_suspension_grid` computes the same atoms from short keys
    (:func:`_signature_classes`).  Its cost is linear in the number of
    generator memberships, so it is meant for tests and small grids.
    """

    level = grid.level
    addresses = grid.base_addresses
    generator_ids: dict[GeneratorKey, int] = {}

    def generator(key: GeneratorKey) -> int:
        value = generator_ids.get(key)
        if value is None:
            value = len(generator_ids)
            generator_ids[key] = value
        return value

    signatures: list[tuple[int, ...]] = []
    for address in addresses:
        signature = [
            generator(
                GeneratorKey(
                    "K",
                    j,
                    (int(address[0]) >> (level - j), int(address[1]) >> (level - j)),
                )
            )
            for j in range(level + 1)
        ]
        signatures.append(tuple(sorted(signature)))

    n_phase = grid.n_phase
    for guard_index in range(grid.n_guard):
        bottom_addresses = addresses[grid.guard_bottom_cells[guard_index]]
        top_addresses = addresses[grid.guard_top_cells[guard_index]]
        bottom_by_level = [
            sorted({(int(a) >> (level - j), int(b) >> (level - j)) for a, b in bottom_addresses})
            for j in range(level + 1)
        ]
        top_by_level = [
            sorted({(int(a) >> (level - j), int(b) >> (level - j)) for a, b in top_addresses})
            for j in range(level + 1)
        ]
        bottom_ids = [
            [generator(GeneratorKey("K", j, cell)) for cell in bottom_by_level[j]]
            for j in range(level + 1)
        ]
        top_ids = [
            [generator(GeneratorKey("K", j, cell)) for cell in top_by_level[j]]
            for j in range(level + 1)
        ]
        for phase in range(n_phase):
            signature: list[int] = []
            for j in range(level + 1):
                coarse_phase = phase >> (level - j)
                last = 2 ** (j + 2) - 1
                if coarse_phase == 0:
                    signature.extend(bottom_ids[j])
                elif coarse_phase == last:
                    signature.extend(top_ids[j])
                else:
                    signature.extend(
                        generator(GeneratorKey("Q", j, cell, coarse_phase))
                        for cell in bottom_by_level[j]
                    )
            signatures.append(tuple(sorted(set(signature))))

    atom_ids: dict[tuple[int, ...], int] = {}
    atom_of_piece = np.empty(len(signatures), dtype=np.int64)
    for piece, signature in enumerate(signatures):
        if not signature:
            raise AssertionError(f"piece {piece} lies in no generator")
        atom = atom_ids.get(signature)
        if atom is None:
            atom = len(atom_ids)
            atom_ids[signature] = atom
        atom_of_piece[piece] = atom
    keys: list[GeneratorKey | None] = [None] * len(generator_ids)
    for key, value in generator_ids.items():
        keys[value] = key
    return tuple(signatures), tuple(keys), atom_of_piece  # type: ignore[arg-type]


def _piece_adjacency(grid: SuspensionGrid) -> sparse.csr_matrix:
    """Pairs of pieces whose closures meet in ``Sigma X`` (symmetric)."""

    rows: list[IntArray] = []
    cols: list[IntArray] = []
    m = grid.cells_per_axis
    addresses = grid.base_addresses

    # Base/base: closed rectangles of the uniform grid meet iff the addresses
    # differ by at most one in each axis.
    for dx in (-1, 0, 1):
        for dy in (-1, 0, 1):
            nx = addresses[:, 0] + dx
            ny = addresses[:, 1] + dy
            ok = (nx >= 0) & (nx < m) & (ny >= 0) & (ny < m)
            neighbor = np.full(addresses.shape[0], -1, dtype=np.int64)
            neighbor[ok] = grid.base_cell_index[nx[ok], ny[ok]]
            keep = neighbor >= 0
            rows.append(np.flatnonzero(keep))
            cols.append(neighbor[keep])

    # Handle/handle in the chart G x [0,1]: consecutive guard intervals share
    # an endpoint, consecutive phase intervals share a phase.
    n_guard, n_phase = grid.n_guard, grid.n_phase
    gi, ki = np.meshgrid(np.arange(n_guard), np.arange(n_phase), indexing="ij")
    gi = gi.ravel()
    ki = ki.ravel()
    source = grid.handle_piece(gi, ki)
    for dg in (-1, 0, 1):
        for dk in (-1, 0, 1):
            ng = gi + dg
            nk = ki + dk
            ok = (ng >= 0) & (ng < n_guard) & (nk >= 0) & (nk < n_phase)
            rows.append(source[ok])
            cols.append(grid.handle_piece(ng[ok], nk[ok]))

    # Base/handle across the identifications: pi(J x {0}) = iota(gamma(J)) and
    # pi(J x {1}) = iota(r(gamma(J))).  The finest cells meeting gamma(J) are
    # those containing gamma at the endpoints or the midpoint of J, because J
    # crosses no grid line in its interior.
    def cells_meeting(curve: Callable[[FloatArray], FloatArray]) -> list[IntArray]:
        a = curve(grid.u_edges[:-1])
        b = curve(grid.u_edges[1:])
        c = curve(0.5 * (grid.u_edges[:-1] + grid.u_edges[1:]))
        located = [grid.locate_base_cells(points) for points in (a, b, c)]
        result: list[IntArray] = []
        for index in range(n_guard):
            result.append(
                np.unique(
                    np.concatenate(
                        [entry.piece[entry.point_index == index] for entry in located]
                    )
                )
            )
        return result

    guard_meets = cells_meeting(grid.guard.gamma)
    reset_meets = cells_meeting(grid.guard.reset)
    for index in range(n_guard):
        bottom = grid.handle_piece(index, 0)
        top = grid.handle_piece(index, n_phase - 1)
        rows.append(np.full(guard_meets[index].size, bottom))
        cols.append(guard_meets[index])
        rows.append(guard_meets[index])
        cols.append(np.full(guard_meets[index].size, bottom))
        rows.append(np.full(reset_meets[index].size, top))
        cols.append(reset_meets[index])
        rows.append(reset_meets[index])
        cols.append(np.full(reset_meets[index].size, top))

    # Handle/handle across the identifications: iota(gamma(J)) meets
    # iota(r(gamma(J'))).  Candidates share a finest cell; the exact test uses
    # the (polyline) curve pieces.
    guard_cell_sets = [set(values.tolist()) for values in guard_meets]
    reset_by_cell: dict[int, list[int]] = {}
    for index, values in enumerate(reset_meets):
        for cell in values.tolist():
            reset_by_cell.setdefault(cell, []).append(index)
    samples = 2 if (grid.guard_profile.straight and grid.reset_profile.straight) else 33
    tolerance = grid.location_tolerance * float(np.min(grid.cell_widths))
    pair_rows: list[int] = []
    pair_cols: list[int] = []
    for index, cells in enumerate(guard_cell_sets):
        candidates = sorted({other for cell in cells for other in reset_by_cell.get(cell, [])})
        if not candidates:
            continue
        guard_polyline = grid.guard.gamma(
            np.linspace(grid.u_edges[index], grid.u_edges[index + 1], samples)
        )
        for other in candidates:
            reset_polyline = grid.guard.reset(
                np.linspace(grid.u_edges[other], grid.u_edges[other + 1], samples)
            )
            if _segments_intersect(guard_polyline, reset_polyline, tolerance):
                bottom = int(grid.handle_piece(index, 0))
                top = int(grid.handle_piece(other, n_phase - 1))
                pair_rows.extend((bottom, top))
                pair_cols.extend((top, bottom))
    rows.append(np.asarray(pair_rows, dtype=np.int64))
    cols.append(np.asarray(pair_cols, dtype=np.int64))

    row = np.concatenate(rows)
    col = np.concatenate(cols)
    adjacency = sparse.csr_matrix(
        (np.ones(row.size), (row, col)), shape=(grid.n_pieces, grid.n_pieces)
    )
    adjacency.data[:] = 1.0
    return adjacency


# ---------------------------------------------------------------------------
# Structural checks mirroring the manuscript
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class SuspensionGridCheck:
    """Piece-level verification of the grid statements of the manuscript."""

    pieces_disjoint_interiors: bool
    pieces_cover_window: bool
    d_injective: bool
    d_base_preimage_exact: bool
    d_contains_interior: bool
    atoms_nonempty: bool

    @property
    def passed(self) -> bool:
        return all(
            (
                self.pieces_disjoint_interiors,
                self.pieces_cover_window,
                self.d_injective,
                self.d_base_preimage_exact,
                self.d_contains_interior,
                self.atoms_nonempty,
            )
        )


def check_suspension_grid(grid: SuspensionGrid) -> SuspensionGridCheck:
    """Verify ``prop:suspension-grid`` and the grid axioms at the piece level.

    * Pieces have pairwise disjoint interiors and cover ``D``: base cells are
      distinct finest cells, handle pieces are products of a partition of
      ``G cap R`` with the phase grid (checked through areas).
    * ``d_n`` is injective and ``iota^{-1}(|d_n(mu)|) = |mu|``: the only base
      piece of ``d_n(mu)`` is ``mu``, and every handle piece of ``d_n(mu)``
      has its seam trace (``gamma(J)`` at phase 0, ``r(gamma(J))`` at phase 1)
      inside ``|mu|``.
    * ``iota(Int|mu|) subset Int|d_n(mu)|``: every seam piece whose trace
      meets ``Int|mu|`` (trace in the single cell ``mu``) belongs to
      ``d_n(mu)``.
    """

    # Base pieces are distinct finest cells of R; handle pieces are products of
    # a partition of G cap R with the phase grid.  Each piece has exactly one
    # atom, so the atoms have disjoint interiors and cover the window.
    disjoint = bool(
        np.unique(grid.base_addresses, axis=0).shape[0] == grid.n_base
        and np.all(np.diff(grid.u_edges) > 0.0)
    )
    cover = bool(
        grid.u_edges[0] == grid.guard.u_bounds[0]
        and grid.u_edges[-1] == grid.guard.u_bounds[1]
        and int(np.count_nonzero(grid.base_cell_index >= 0)) == grid.n_base
        and grid.atom_of_piece.shape[0] == grid.n_pieces
        and np.all((grid.atom_of_piece >= 0) & (grid.atom_of_piece < grid.n_atoms))
    )

    d_injective = bool(np.unique(grid.d_map).size == grid.n_base)
    owner = np.full(grid.n_atoms, -1, dtype=np.int64)
    owner[grid.d_map] = np.arange(grid.n_base)
    base_count = np.bincount(grid.atom_of_piece[: grid.n_base], minlength=grid.n_atoms)
    preimage_exact = bool(np.all(base_count[grid.d_map] == 1))
    contains_interior = True
    for index in range(grid.n_guard):
        for phase, cells in (
            (0, grid.guard_bottom_cells[index]),
            (grid.n_phase - 1, grid.guard_top_cells[index]),
        ):
            atom = int(grid.atom_of_piece[grid.handle_piece(index, phase)])
            mu = int(owner[atom])
            if mu >= 0 and mu not in set(cells.tolist()):
                # A seam piece of d_n(mu) must have its trace inside |mu|.
                preimage_exact = False
            if cells.size == 1 and grid.d_map[cells[0]] != atom:
                # A trace in a single cell mu (relative interior) forces the
                # seam piece into the atom containing iota(Int|mu|).
                contains_interior = False
    # Middle phase pieces never meet iota(X) and must avoid d_n(X_n).
    guard_index, phase = grid.handle_indices(np.arange(grid.n_base, grid.n_pieces))
    middle = (phase > 0) & (phase < grid.n_phase - 1)
    if np.any(owner[grid.atom_of_piece[grid.n_base :][middle]] >= 0):
        preimage_exact = False
    atoms_nonempty = bool(np.all(np.diff(grid.atom_offsets) > 0))
    return SuspensionGridCheck(
        pieces_disjoint_interiors=disjoint,
        pieces_cover_window=cover,
        d_injective=d_injective,
        d_base_preimage_exact=preimage_exact,
        d_contains_interior=contains_interior,
        atoms_nonempty=atoms_nonempty,
    )


__all__ = [
    "BASE_PIECE",
    "HANDLE_PIECE",
    "DyadicBaseWindow",
    "GeneratorKey",
    "GuardResetSpec",
    "LocatedPoints",
    "SuspensionGrid",
    "SuspensionGridCheck",
    "UnsupportedSuspensionGridError",
    "build_suspension_grid",
    "check_suspension_grid",
    "reference_signatures",
]
