"""Exit-aware local index pairs for persisted CMGDB Atlas relations.

This module works at the level of a finite, already persisted Atlas relation.
It does not resample a hybrid trajectory and does not infer a continuous-system
Conley index.  Starting from a recorded Morse SCC ``S``, it constructs a
geometric collar ``N`` and the least represented exit set ``L`` generated by

* source flags saying that an image has an open/ambient exit, and
* represented relation edges from a source in ``N`` to a target outside ``N``.

It then closes ``L`` under represented images inside ``N``.  The resulting
certificate explicitly checks

``F(N \\ L) subset N`` and ``F(L) intersection N subset L``, rejects
``S intersection L``, and verifies that ``S`` is the only recurrent component
of the represented relation in ``N \\ L``.

Atlas rectangles may have arbitrary sizes.  No uniform-grid or single-depth
assumption is made.  Same-chart collar adjacency is closed-box contact;
cross-chart reset identifications must be supplied as explicit quotient
neighbor pairs.
"""

from __future__ import annotations

import gzip
import hashlib
import itertools
import json
from collections.abc import Iterable, Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path
from types import MappingProxyType
from typing import Any

import networkx as nx
import numpy as np
from scipy.spatial import cKDTree


EXIT_AWARE_LOCAL_INDEX_INPUT_SCHEMA = "exit-aware-local-index-input-v1"
EXIT_AWARE_LOCAL_INDEX_CERTIFICATE_SCHEMA = (
    "exit-aware-local-index-pair-certificate-v1"
)
GARCIA_WALKER_OPEN_EXIT_RELATION_SCHEMA = (
    "garcia-walker-open-exit-atlas-relation-v1"
)


def _frozen_bool_mapping(values: Mapping[int, bool]) -> Mapping[int, bool]:
    normalized = {}
    for source, flag in values.items():
        if not isinstance(flag, bool):
            raise ValueError(f"open-exit flag for cell {source} must be boolean")
        normalized[int(source)] = flag
    if len(normalized) != len(values):
        raise ValueError("source-exit flags contain duplicate integer ids")
    return MappingProxyType(normalized)


def _normalized_pairs(
    pairs: Iterable[Sequence[int]],
    *,
    name: str,
) -> tuple[tuple[int, int], ...]:
    normalized: set[tuple[int, int]] = set()
    for raw_pair in pairs:
        pair = tuple(int(value) for value in raw_pair)
        if len(pair) != 2:
            raise ValueError(f"every {name} entry must contain two cell ids")
        if pair[0] == pair[1]:
            raise ValueError(f"{name} must not contain self-pairs")
        normalized.add(tuple(sorted(pair)))
    return tuple(sorted(normalized))


@dataclass(frozen=True)
class ExitAwareLocalIndexInput:
    """Serializable inputs not already contained in an Atlas relation cache."""

    morse_node: int
    collar_layers: int
    open_exit_flags: Mapping[int, bool]
    allowed_cells: frozenset[int] | None = None
    quotient_neighbor_pairs: tuple[tuple[int, int], ...] = ()
    metadata: Mapping[str, object] = MappingProxyType({})

    def __post_init__(self) -> None:
        if int(self.collar_layers) < 0:
            raise ValueError("collar_layers must be nonnegative")
        allowed = (
            None
            if self.allowed_cells is None
            else frozenset(int(cell) for cell in self.allowed_cells)
        )
        if allowed is not None and not allowed:
            raise ValueError("allowed_cells must be nonempty when supplied")
        object.__setattr__(self, "morse_node", int(self.morse_node))
        object.__setattr__(self, "collar_layers", int(self.collar_layers))
        object.__setattr__(
            self,
            "open_exit_flags",
            _frozen_bool_mapping(self.open_exit_flags),
        )
        object.__setattr__(self, "allowed_cells", allowed)
        object.__setattr__(
            self,
            "quotient_neighbor_pairs",
            _normalized_pairs(
                self.quotient_neighbor_pairs,
                name="quotient_neighbor_pairs",
            ),
        )
        object.__setattr__(self, "metadata", MappingProxyType(dict(self.metadata)))

    def to_json_dict(self) -> dict[str, object]:
        return {
            "schema": EXIT_AWARE_LOCAL_INDEX_INPUT_SCHEMA,
            "morse_node": self.morse_node,
            "collar_layers": self.collar_layers,
            "allowed_cells": (
                None
                if self.allowed_cells is None
                else sorted(self.allowed_cells)
            ),
            "source_exit_flags": [
                {"source": source, "open_exit": flag}
                for source, flag in sorted(self.open_exit_flags.items())
            ],
            "quotient_neighbor_pairs": [
                list(pair) for pair in self.quotient_neighbor_pairs
            ],
            "metadata": dict(self.metadata),
        }

    def write_json(self, path: str | Path) -> Path:
        target = Path(path)
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(
            json.dumps(self.to_json_dict(), indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )
        return target

    @classmethod
    def read_json(cls, path: str | Path) -> "ExitAwareLocalIndexInput":
        source = Path(path)
        payload = json.loads(source.read_text(encoding="utf-8"))
        if payload.get("schema") != EXIT_AWARE_LOCAL_INDEX_INPUT_SCHEMA:
            raise ValueError(f"{source} has an unsupported local-index input schema")
        raw_flags = payload.get("source_exit_flags", [])
        if not isinstance(raw_flags, list):
            raise ValueError("source_exit_flags must be a list")
        flags: dict[int, bool] = {}
        for record in raw_flags:
            if not isinstance(record, dict):
                raise ValueError("each source-exit flag must be an object")
            source_id = int(record["source"])
            if source_id in flags:
                raise ValueError(f"duplicate source-exit flag for cell {source_id}")
            flag = record.get("open_exit")
            if not isinstance(flag, bool):
                raise ValueError(f"open_exit for cell {source_id} must be boolean")
            flags[source_id] = flag
        raw_allowed = payload.get("allowed_cells")
        allowed = (
            None
            if raw_allowed is None
            else frozenset(int(cell) for cell in raw_allowed)
        )
        metadata = payload.get("metadata", {})
        if not isinstance(metadata, dict):
            raise ValueError("input metadata must be an object")
        return cls(
            morse_node=int(payload["morse_node"]),
            collar_layers=int(payload["collar_layers"]),
            open_exit_flags=flags,
            allowed_cells=allowed,
            quotient_neighbor_pairs=tuple(
                tuple(int(value) for value in pair)
                for pair in payload.get("quotient_neighbor_pairs", [])
            ),
            metadata=metadata,
        )


@dataclass(frozen=True)
class _Rectangle:
    index: int
    chart_id: int
    lower: tuple[float, ...]
    upper: tuple[float, ...]

    @property
    def dimension(self) -> int:
        return len(self.lower)

    @property
    def center(self) -> tuple[float, ...]:
        return tuple(
            (lower + upper) / 2.0
            for lower, upper in zip(self.lower, self.upper)
        )

    @property
    def half_width(self) -> tuple[float, ...]:
        return tuple(
            (upper - lower) / 2.0
            for lower, upper in zip(self.lower, self.upper)
        )

    @property
    def width(self) -> tuple[float, ...]:
        return tuple(
            upper - lower for lower, upper in zip(self.lower, self.upper)
        )


@dataclass(frozen=True)
class _PersistedRelationCell:
    """Minimal cell contract shared by both supported persistence schemas."""

    index: int
    chart_id: int
    bounds: tuple[float, ...]
    image: tuple[int, ...]
    morse_node: int | None
    relation_evaluated: bool
    axis_depth: int | None = None
    coordinates: tuple[int, ...] | None = None


@dataclass(frozen=True)
class _PersistedRelation:
    model: str
    depth: int
    t_star: float
    cells: tuple[_PersistedRelationCell, ...]
    relation_scope: str
    whole_cell_outer_enclosure_certified: bool

    def morse_set(self, node: int) -> frozenset[int]:
        result = frozenset(
            cell.index for cell in self.cells if cell.morse_node == int(node)
        )
        if not result:
            raise ValueError(f"Morse node {node} has no cells in this relation")
        return result


@dataclass(frozen=True)
class LoadedExitAwareRelation:
    """Normalized relation plus any exit/collar data embedded in its cache."""

    snapshot: Any
    persistence_schema: str
    embedded_open_exit_flags: Mapping[int, bool]
    embedded_morse_node: int | None = None
    embedded_allowed_cells: frozenset[int] | None = None
    embedded_quotient_neighbor_pairs: tuple[tuple[int, int], ...] = ()

    def __post_init__(self) -> None:
        object.__setattr__(
            self,
            "embedded_open_exit_flags",
            _frozen_bool_mapping(self.embedded_open_exit_flags),
        )
        object.__setattr__(
            self,
            "embedded_quotient_neighbor_pairs",
            _normalized_pairs(
                self.embedded_quotient_neighbor_pairs,
                name="embedded_quotient_neighbor_pairs",
            ),
        )


@dataclass(frozen=True)
class GeometricCollar:
    """A finite collar and the geometry certificate used to construct it."""

    n_cells: frozenset[int]
    shells: tuple[tuple[int, ...], ...]
    neighbor_edges: tuple[tuple[int, int], ...]
    quotient_neighbor_edges: tuple[tuple[int, int], ...]
    allowed_cells: frozenset[int]
    chart_dimensions: Mapping[int, int]
    width_vectors_by_chart: Mapping[int, tuple[tuple[float, ...], ...]]
    mixed_cell_sizes: bool
    contact_algorithm: str
    tolerance: float

    def summary(self) -> dict[str, object]:
        return {
            "construction": (
                "same-chart closed-rectangle contact plus explicit "
                "reset-quotient neighbor pairs"
            ),
            "uniform_grid_assumed": False,
            "mixed_depth_or_adaptive_cells_supported": True,
            "mixed_cell_sizes_present": self.mixed_cell_sizes,
            "same_chart_contact_algorithm": self.contact_algorithm,
            "contact_tolerance": self.tolerance,
            "requested_layers": len(self.shells) - 1,
            "allowed_cells": len(self.allowed_cells),
            "allowed_cell_ids": sorted(self.allowed_cells),
            "N_cells": len(self.n_cells),
            "shells": [list(shell) for shell in self.shells],
            "shell_sizes": [len(shell) for shell in self.shells],
            "same_chart_neighbor_edges": len(self.neighbor_edges),
            "quotient_neighbor_edges": [
                list(edge) for edge in self.quotient_neighbor_edges
            ],
            "chart_dimensions": {
                str(chart): dimension
                for chart, dimension in sorted(self.chart_dimensions.items())
            },
            "width_vectors_by_chart": {
                str(chart): [list(widths) for widths in vectors]
                for chart, vectors in sorted(self.width_vectors_by_chart.items())
            },
        }


@dataclass(frozen=True)
class ExitAwareLocalIndexPairCertificate:
    """Complete pass/fail witness for one finite-relation local pair."""

    model: str
    depth: int
    t_star: float
    relation_scope: str
    persistence_schema: str | None
    relation_sha256: str | None
    morse_node: int
    specification_metadata: Mapping[str, object]
    s_cells: frozenset[int]
    collar: GeometricCollar
    ambient_exit_sources: tuple[int, ...]
    relation_exit_edges: tuple[tuple[int, tuple[int, ...]], ...]
    unevaluated_n_sources: tuple[int, ...]
    missing_open_exit_flags: tuple[int, ...]
    initial_l_cells: frozenset[int]
    closure_rounds: tuple[tuple[int, ...], ...]
    l_cells: frozenset[int]
    first_condition_violations: tuple[tuple[int, tuple[int, ...]], ...]
    second_condition_violations: tuple[tuple[int, tuple[int, ...]], ...]
    s_intersection_l: tuple[int, ...]
    recurrent_components_in_core: tuple[tuple[int, ...], ...]
    unexpected_recurrent_components: tuple[tuple[int, ...], ...]
    s_is_recurrent_component: bool
    whole_cell_outer_enclosure_certified: bool

    @property
    def finite_relation_pair_certified(self) -> bool:
        return bool(
            not self.unevaluated_n_sources
            and not self.missing_open_exit_flags
            and not self.first_condition_violations
            and not self.second_condition_violations
            and not self.s_intersection_l
            and self.s_is_recurrent_component
            and not self.unexpected_recurrent_components
        )

    @property
    def continuous_system_index_pair_certified(self) -> bool:
        return False

    @property
    def n_cells(self) -> frozenset[int]:
        return self.collar.n_cells

    @property
    def core_cells(self) -> frozenset[int]:
        return self.n_cells - self.l_cells

    def to_json_dict(self) -> dict[str, object]:
        blockers = []
        if self.unevaluated_n_sources:
            blockers.append("unevaluated_sources_inside_N")
        if self.missing_open_exit_flags:
            blockers.append("missing_open_exit_flags_inside_N")
        if self.first_condition_violations:
            blockers.append("F_of_N_minus_L_not_subset_N")
        if self.second_condition_violations:
            blockers.append("F_of_L_intersection_N_not_subset_L")
        if self.s_intersection_l:
            blockers.append("S_intersects_L")
        if not self.s_is_recurrent_component:
            blockers.append("S_not_a_recurrent_component_of_N_minus_L")
        if self.unexpected_recurrent_components:
            blockers.append("additional_recurrent_components_in_N_minus_L")
        continuous_blockers = ["no_external_continuous_index_pair_theorem"]
        if not self.whole_cell_outer_enclosure_certified:
            continuous_blockers.insert(0, "whole_cell_outer_enclosure_not_certified")
        return {
            "schema": EXIT_AWARE_LOCAL_INDEX_CERTIFICATE_SCHEMA,
            "model": self.model,
            "depth": self.depth,
            "t_star": self.t_star,
            "morse_node": self.morse_node,
            "specification_metadata": dict(self.specification_metadata),
            "relation_provenance": {
                "scope": self.relation_scope,
                "persistence_schema": self.persistence_schema,
                "sha256": self.relation_sha256,
                "whole_cell_outer_enclosure_certified": (
                    self.whole_cell_outer_enclosure_certified
                ),
            },
            "result_scope": "finite_persisted_atlas_relation",
            "S_cells": sorted(self.s_cells),
            "N_cells": sorted(self.n_cells),
            "L_cells": sorted(self.l_cells),
            "N_minus_L_cells": sorted(self.core_cells),
            "geometric_collar": self.collar.summary(),
            "exit_construction": {
                "ambient_exit_sources": list(self.ambient_exit_sources),
                "relation_exit_edges": [
                    [source, list(targets)]
                    for source, targets in self.relation_exit_edges
                ],
                "unevaluated_N_sources": list(self.unevaluated_n_sources),
                "missing_open_exit_flags": list(self.missing_open_exit_flags),
                "initial_L_cells": sorted(self.initial_l_cells),
                "closure_rule": "L_next = L union (F(L) intersection N)",
                "closure_rounds": [list(round_) for round_ in self.closure_rounds],
                "least_closed_exit_set_verified": True,
            },
            "pair_checks": {
                "first_condition": "F(N\\L) subset N",
                "first_condition_violations": [
                    [source, list(targets)]
                    for source, targets in self.first_condition_violations
                ],
                "second_condition": "F(L) intersection N subset L",
                "second_condition_violations": [
                    [source, list(targets)]
                    for source, targets in self.second_condition_violations
                ],
                "S_intersection_L": list(self.s_intersection_l),
                "recurrent_components_in_N_minus_L": [
                    list(component)
                    for component in self.recurrent_components_in_core
                ],
                "unexpected_recurrent_components": [
                    list(component)
                    for component in self.unexpected_recurrent_components
                ],
                "S_is_recurrent_component": self.s_is_recurrent_component,
            },
            "finite_relation_pair_blockers": blockers,
            "finite_relation_pair_certified": self.finite_relation_pair_certified,
            "continuous_system_blockers": continuous_blockers,
            "continuous_system_index_pair_certified": False,
        }

    def write_json(self, path: str | Path) -> Path:
        target = Path(path)
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(
            json.dumps(self.to_json_dict(), indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )
        return target


def sha256_file(path: str | Path) -> str:
    """Return the SHA-256 digest of a persisted relation cache."""

    digest = hashlib.sha256()
    with Path(path).open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def _morse_membership_from_payload(
    payload: Mapping[str, object],
    raw_cells: Sequence[Mapping[str, object]],
) -> dict[int, int]:
    membership: dict[int, int] = {}
    for raw_cell in raw_cells:
        raw_node = raw_cell.get("morse_node")
        if raw_node is not None:
            membership[int(raw_cell["index"])] = int(raw_node)

    morse_graph = payload.get("morse_graph", {})
    if not isinstance(morse_graph, dict):
        raise ValueError("walker relation morse_graph must be an object")
    raw_sets = morse_graph.get("morse_sets", {})
    parsed_sets: list[tuple[int, Sequence[object]]] = []
    if isinstance(raw_sets, dict):
        for node, cells in raw_sets.items():
            if not isinstance(cells, (list, tuple)):
                raise ValueError("walker morse-set cells must be a list")
            parsed_sets.append((int(node), cells))
    elif isinstance(raw_sets, list):
        for position, record in enumerate(raw_sets):
            if isinstance(record, dict):
                node = int(record.get("node", record.get("morse_node", position)))
                cells = record.get("cells", record.get("cell_ids", []))
            else:
                node = position
                cells = record
            if not isinstance(cells, (list, tuple)):
                raise ValueError("walker morse-set cells must be a list")
            parsed_sets.append((node, cells))
    elif raw_sets is not None:
        raise ValueError("walker relation morse_sets must be an object or list")

    for node, raw_members in parsed_sets:
        for raw_member in raw_members:
            member = int(raw_member)
            previous = membership.get(member)
            if previous is not None and previous != node:
                raise ValueError(
                    f"cell {member} has conflicting Morse nodes {previous} and {node}"
                )
            membership[member] = node
    return membership


def _optional_cell_set(
    payload: Mapping[str, object],
    key: str,
) -> frozenset[int] | None:
    raw = payload.get(key)
    if raw is None:
        return None
    if not isinstance(raw, list):
        raise ValueError(f"{key} must be a list of cell ids")
    return frozenset(int(cell) for cell in raw)


def _flatten_rectangle_bounds(
    raw_bounds: object,
    *,
    cell_index: int,
) -> tuple[float, ...]:
    if not isinstance(raw_bounds, (list, tuple)) or not raw_bounds:
        raise ValueError(f"cell {cell_index} bounds must be a nonempty list")
    if all(
        isinstance(interval, (list, tuple)) and len(interval) == 2
        for interval in raw_bounds
    ):
        intervals = tuple(
            tuple(float(value) for value in interval) for interval in raw_bounds
        )
        return tuple(interval[0] for interval in intervals) + tuple(
            interval[1] for interval in intervals
        )
    return tuple(float(value) for value in raw_bounds)


def _walker_chart_domains(
    payload: Mapping[str, object],
) -> dict[int, tuple[tuple[float, float], ...]]:
    raw_charts = payload.get("charts")
    if not isinstance(raw_charts, dict) or not raw_charts:
        raise ValueError("walker relation must persist its Atlas chart domains")
    domains: dict[int, tuple[tuple[float, float], ...]] = {}
    for raw_chart in raw_charts.values():
        if not isinstance(raw_chart, dict):
            raise ValueError("every walker chart record must be an object")
        chart_id = int(raw_chart["chart_id"])
        raw_bounds = raw_chart.get("bounds")
        if not isinstance(raw_bounds, list) or not raw_bounds:
            raise ValueError(f"walker chart {chart_id} has no bounds")
        intervals = tuple(
            (float(interval[0]), float(interval[1]))
            for interval in raw_bounds
            if isinstance(interval, (list, tuple)) and len(interval) == 2
        )
        if len(intervals) != len(raw_bounds):
            raise ValueError(f"walker chart {chart_id} has malformed bounds")
        if any(lower >= upper for lower, upper in intervals):
            raise ValueError(f"walker chart {chart_id} has a degenerate interval")
        if chart_id in domains:
            raise ValueError(f"walker relation repeats Atlas chart {chart_id}")
        domains[chart_id] = intervals
    return domains


def _validated_dyadic_geometry(
    raw_cell: Mapping[str, object],
    bounds: tuple[float, ...],
    chart_domains: Mapping[int, tuple[tuple[float, float], ...]],
    *,
    tolerance: float = 1.0e-11,
) -> tuple[int, tuple[int, ...]]:
    index = int(raw_cell["index"])
    chart_id = int(raw_cell["chart_id"])
    if chart_id not in chart_domains:
        raise ValueError(f"cell {index} refers to unknown chart {chart_id}")
    axis_depth = int(raw_cell["axis_depth"])
    raw_coordinates = raw_cell.get("coordinates")
    if axis_depth < 0 or not isinstance(raw_coordinates, list):
        raise ValueError(f"cell {index} has malformed dyadic metadata")
    coordinates = tuple(int(value) for value in raw_coordinates)
    domain = chart_domains[chart_id]
    if len(coordinates) != len(domain) or len(bounds) != 2 * len(domain):
        raise ValueError(f"cell {index} dyadic dimension disagrees with its chart")
    subdivisions = 2**axis_depth
    if any(value < 0 or value >= subdivisions for value in coordinates):
        raise ValueError(f"cell {index} dyadic coordinates lie outside its chart")
    expected_lower = tuple(
        lower + (upper - lower) * coordinate / subdivisions
        for (lower, upper), coordinate in zip(domain, coordinates)
    )
    expected_upper = tuple(
        lower + (upper - lower) * (coordinate + 1) / subdivisions
        for (lower, upper), coordinate in zip(domain, coordinates)
    )
    expected = (*expected_lower, *expected_upper)
    if not np.allclose(bounds, expected, rtol=0.0, atol=tolerance):
        raise ValueError(
            f"cell {index} bounds disagree with axis_depth/coordinates"
        )
    return axis_depth, coordinates


def _walker_open_exit_relation(
    payload: Mapping[str, object],
) -> LoadedExitAwareRelation:
    metadata = payload.get("metadata", {})
    if not isinstance(metadata, dict):
        raise ValueError("walker relation metadata must be an object")
    raw_cells = payload.get("cells")
    if not isinstance(raw_cells, list) or not raw_cells:
        raise ValueError("walker relation must contain a nonempty cells list")
    if any(not isinstance(cell, dict) for cell in raw_cells):
        raise ValueError("every walker relation cell must be an object")
    typed_cells = tuple(raw_cells)
    membership = _morse_membership_from_payload(payload, typed_cells)
    chart_domains = _walker_chart_domains(payload)

    cells = []
    embedded_flags: dict[int, bool] = {}
    for raw_cell in typed_cells:
        index = int(raw_cell["index"])
        bounds = _flatten_rectangle_bounds(
            raw_cell["bounds"],
            cell_index=index,
        )
        axis_depth, coordinates = _validated_dyadic_geometry(
            raw_cell,
            bounds,
            chart_domains,
        )
        open_exit = raw_cell.get("open_exit")
        if open_exit is not None:
            if not isinstance(open_exit, dict):
                raise ValueError(f"cell {index} open_exit must be an object")
            flag = open_exit.get("has_open_exit")
            if not isinstance(flag, bool):
                raise ValueError(
                    f"cell {index} open_exit.has_open_exit must be boolean"
                )
            embedded_flags[index] = flag
        relation_evaluated = raw_cell.get("relation_evaluated", True)
        if not isinstance(relation_evaluated, bool):
            raise ValueError(
                f"cell {index} relation_evaluated must be boolean"
            )
        cells.append(
            _PersistedRelationCell(
                index=index,
                chart_id=int(raw_cell["chart_id"]),
                bounds=bounds,
                image=tuple(int(target) for target in raw_cell.get("image", [])),
                morse_node=membership.get(index),
                relation_evaluated=relation_evaluated,
                axis_depth=axis_depth,
                coordinates=coordinates,
            )
        )
    cells.sort(key=lambda cell: cell.index)
    if tuple(cell.index for cell in cells) != tuple(range(len(cells))):
        raise ValueError("walker relation cells must be indexed consecutively")

    def value(name: str, *alternatives: str, default: object | None = None) -> object:
        for key in (name, *alternatives):
            if key in payload:
                return payload[key]
            if key in metadata:
                return metadata[key]
        if default is not None:
            return default
        raise ValueError(f"walker relation is missing {name}")

    enclosure_certified = value(
        "whole_cell_outer_enclosure_certified",
        default=False,
    )
    if not isinstance(enclosure_certified, bool):
        raise ValueError(
            "whole_cell_outer_enclosure_certified must be boolean"
        )
    snapshot = _PersistedRelation(
        model=str(value("model")),
        depth=int(value("depth", "atlas_depth")),
        t_star=float(value("t_star", "tau")),
        cells=tuple(cells),
        relation_scope=str(
            value("relation_scope", default="adaptive_local_atlas_relation")
        ),
        whole_cell_outer_enclosure_certified=enclosure_certified,
    )
    embedded_allowed = _optional_cell_set(payload, "allowed_cells")
    candidate = payload.get("candidate", {})
    if not isinstance(candidate, dict):
        raise ValueError("walker relation candidate must be an object")
    raw_candidate_node = candidate.get("morse_node")
    candidate_node = (
        None if raw_candidate_node is None else int(raw_candidate_node)
    )
    raw_pairs = payload.get("quotient_neighbor_pairs", [])
    if not isinstance(raw_pairs, list):
        raise ValueError("quotient_neighbor_pairs must be a list")
    return LoadedExitAwareRelation(
        snapshot=snapshot,
        persistence_schema=GARCIA_WALKER_OPEN_EXIT_RELATION_SCHEMA,
        embedded_open_exit_flags=embedded_flags,
        embedded_morse_node=candidate_node,
        embedded_allowed_cells=embedded_allowed,
        embedded_quotient_neighbor_pairs=tuple(
            tuple(int(value) for value in pair) for pair in raw_pairs
        ),
    )


def load_exit_aware_relation(path: str | Path) -> LoadedExitAwareRelation:
    """Load either the generic physical cache or the walker open-exit cache."""

    source = Path(path)
    with gzip.open(source, "rt", encoding="utf-8") as stream:
        payload = json.load(stream)
    schema = payload.get("schema")
    if schema == GARCIA_WALKER_OPEN_EXIT_RELATION_SCHEMA:
        return _walker_open_exit_relation(payload)
    if schema == "physical-conley-atlas-relation-v1":
        # Import lazily to keep the generic geometry layer independent of the
        # physical nerve/carrier implementation during ordinary use.
        from .physical_conley import AtlasRelationSnapshot

        return LoadedExitAwareRelation(
            snapshot=AtlasRelationSnapshot.read_gzip_json(source),
            persistence_schema=str(schema),
            embedded_open_exit_flags={},
        )
    raise ValueError(f"{source} has unsupported relation schema {schema!r}")


def merge_relation_inputs(
    specification: ExitAwareLocalIndexInput,
    loaded_relation: LoadedExitAwareRelation,
) -> ExitAwareLocalIndexInput:
    """Merge embedded flags/seams with an external collar specification."""

    merged_flags = dict(loaded_relation.embedded_open_exit_flags)
    conflicts = {
        source: (merged_flags[source], flag)
        for source, flag in specification.open_exit_flags.items()
        if source in merged_flags and merged_flags[source] != flag
    }
    if conflicts:
        raise ValueError(
            "external open-exit flags contradict persisted relation flags: "
            f"{conflicts!r}"
        )
    merged_flags.update(specification.open_exit_flags)
    allowed = (
        specification.allowed_cells
        if specification.allowed_cells is not None
        else loaded_relation.embedded_allowed_cells
    )
    quotient_pairs = tuple(
        sorted(
            set(loaded_relation.embedded_quotient_neighbor_pairs)
            | set(specification.quotient_neighbor_pairs)
        )
    )
    return ExitAwareLocalIndexInput(
        morse_node=specification.morse_node,
        collar_layers=specification.collar_layers,
        open_exit_flags=merged_flags,
        allowed_cells=allowed,
        quotient_neighbor_pairs=quotient_pairs,
        metadata=specification.metadata,
    )


def _rectangles(snapshot: Any) -> tuple[_Rectangle, ...]:
    cells = tuple(snapshot.cells)
    if tuple(int(cell.index) for cell in cells) != tuple(range(len(cells))):
        raise ValueError("relation cells must be indexed consecutively")
    rectangles = []
    chart_dimensions: dict[int, int] = {}
    for cell in cells:
        bounds = tuple(float(value) for value in cell.bounds)
        if not bounds or len(bounds) % 2:
            raise ValueError(f"cell {cell.index} has malformed rectangle bounds")
        dimension = len(bounds) // 2
        if not all(np.isfinite(value) for value in bounds):
            raise ValueError(f"cell {cell.index} has non-finite rectangle bounds")
        lower = bounds[:dimension]
        upper = bounds[dimension:]
        if any(left >= right for left, right in zip(lower, upper)):
            raise ValueError(f"cell {cell.index} is not a positive-volume top cell")
        chart_id = int(cell.chart_id)
        previous = chart_dimensions.setdefault(chart_id, dimension)
        if previous != dimension:
            raise ValueError(f"Atlas chart {chart_id} mixes rectangle dimensions")
        rectangles.append(
            _Rectangle(
                index=int(cell.index),
                chart_id=chart_id,
                lower=lower,
                upper=upper,
            )
        )
    return tuple(rectangles)


def _closed_boxes_intersect(
    first: _Rectangle,
    second: _Rectangle,
    *,
    tolerance: float,
) -> bool:
    return all(
        left_lower <= right_upper + tolerance
        and right_lower <= left_upper + tolerance
        for left_lower, left_upper, right_lower, right_upper in zip(
            first.lower,
            first.upper,
            second.lower,
            second.upper,
        )
    )


def _interiors_overlap(
    first: _Rectangle,
    second: _Rectangle,
    *,
    tolerance: float,
) -> bool:
    return all(
        max(left_lower, right_lower) < min(left_upper, right_upper) - tolerance
        for left_lower, left_upper, right_lower, right_upper in zip(
            first.lower,
            first.upper,
            second.lower,
            second.upper,
        )
    )


def _kdtree_same_chart_contact_edges(
    rectangles: Sequence[_Rectangle],
    allowed_cells: frozenset[int],
    *,
    tolerance: float,
) -> tuple[tuple[int, int], ...]:
    """Build contact edges without assuming equal box widths or one depth."""

    by_chart: dict[int, list[_Rectangle]] = {}
    for rectangle in rectangles:
        if rectangle.index in allowed_cells:
            by_chart.setdefault(rectangle.chart_id, []).append(rectangle)

    edges: set[tuple[int, int]] = set()
    overlap_witnesses: list[tuple[int, int]] = []
    for chart_rectangles in by_chart.values():
        centers = np.asarray(
            [rectangle.center for rectangle in chart_rectangles],
            dtype=float,
        )
        half_widths = np.asarray(
            [rectangle.half_width for rectangle in chart_rectangles],
            dtype=float,
        )
        if not len(chart_rectangles):
            continue
        tree = cKDTree(centers)
        global_half_width = np.max(half_widths, axis=0)
        for local_index, rectangle in enumerate(chart_rectangles):
            search_radius = float(
                np.max(half_widths[local_index] + global_half_width) + tolerance
            )
            candidates = tree.query_ball_point(
                centers[local_index],
                search_radius,
                p=np.inf,
            )
            for candidate_index in candidates:
                if candidate_index <= local_index:
                    continue
                candidate = chart_rectangles[int(candidate_index)]
                if not _closed_boxes_intersect(
                    rectangle,
                    candidate,
                    tolerance=tolerance,
                ):
                    continue
                pair = tuple(sorted((rectangle.index, candidate.index)))
                if _interiors_overlap(
                    rectangle,
                    candidate,
                    tolerance=tolerance,
                ):
                    overlap_witnesses.append(pair)
                edges.add(pair)
    if overlap_witnesses:
        raise ValueError(
            "same-chart active top cells have overlapping interiors: "
            f"{sorted(set(overlap_witnesses))[:12]!r}"
        )
    return tuple(sorted(edges))


def _dyadic_same_chart_contact_edges(
    relation_cells: Sequence[object],
    rectangles: Sequence[_Rectangle],
    allowed_cells: frozenset[int],
    *,
    tolerance: float,
) -> tuple[tuple[int, int], ...] | None:
    """Use dyadic addresses when every allowed cell persists one."""

    dyadic: dict[int, tuple[int, int, tuple[int, ...]]] = {}
    for source in sorted(allowed_cells):
        cell = relation_cells[source]
        raw_depth = getattr(cell, "axis_depth", None)
        raw_coordinates = getattr(cell, "coordinates", None)
        if raw_depth is None or raw_coordinates is None:
            return None
        depth = int(raw_depth)
        coordinates = tuple(int(value) for value in raw_coordinates)
        rectangle = rectangles[source]
        if depth < 0 or len(coordinates) != rectangle.dimension:
            raise ValueError(f"cell {source} has malformed dyadic contact metadata")
        subdivisions = 2**depth
        if any(value < 0 or value >= subdivisions for value in coordinates):
            raise ValueError(f"cell {source} has out-of-range dyadic coordinates")
        dyadic[source] = (rectangle.chart_id, depth, coordinates)

    lookup: dict[tuple[int, int, tuple[int, ...]], int] = {}
    depths_by_chart: dict[int, set[int]] = {}
    for source, descriptor in dyadic.items():
        if descriptor in lookup:
            raise ValueError(
                "two allowed cells have the same dyadic descriptor: "
                f"{descriptor!r}"
            )
        lookup[descriptor] = source
        depths_by_chart.setdefault(descriptor[0], set()).add(descriptor[1])

    edges: set[tuple[int, int]] = set()
    overlap_witnesses: list[tuple[int, int]] = []
    for source, (chart_id, depth, coordinates) in dyadic.items():
        for candidate_depth in sorted(depths_by_chart[chart_id]):
            if candidate_depth > depth:
                # Every fine/coarse pair is discovered while visiting its fine
                # member; this avoids enumerating all descendants of a coarse
                # adaptive leaf.
                continue
            scale = 2 ** (depth - candidate_depth)
            coordinate_ranges = []
            for coordinate in coordinates:
                lower = max(0, (coordinate - 1) // scale)
                upper = min(2**candidate_depth - 1, (coordinate + 1) // scale)
                coordinate_ranges.append(range(lower, upper + 1))
            for candidate_coordinates in itertools.product(*coordinate_ranges):
                target = lookup.get(
                    (chart_id, candidate_depth, tuple(candidate_coordinates))
                )
                if target is None or target == source:
                    continue
                pair = tuple(sorted((source, target)))
                if pair in edges:
                    continue
                first, second = (rectangles[pair[0]], rectangles[pair[1]])
                if not _closed_boxes_intersect(
                    first,
                    second,
                    tolerance=tolerance,
                ):
                    continue
                if _interiors_overlap(first, second, tolerance=tolerance):
                    overlap_witnesses.append(pair)
                edges.add(pair)
    if overlap_witnesses:
        raise ValueError(
            "same-chart active top cells have overlapping interiors: "
            f"{sorted(set(overlap_witnesses))[:12]!r}"
        )
    return tuple(sorted(edges))


def _same_chart_contact_edges(
    relation_cells: Sequence[object],
    rectangles: Sequence[_Rectangle],
    allowed_cells: frozenset[int],
    *,
    tolerance: float,
) -> tuple[tuple[tuple[int, int], ...], str]:
    dyadic_edges = _dyadic_same_chart_contact_edges(
        relation_cells,
        rectangles,
        allowed_cells,
        tolerance=tolerance,
    )
    if dyadic_edges is not None:
        return dyadic_edges, "dyadic-coordinate lookup"
    return (
        _kdtree_same_chart_contact_edges(
            rectangles,
            allowed_cells,
            tolerance=tolerance,
        ),
        "adaptive rectangle KD-tree with exact intersection filter",
    )


def build_geometric_collar(
    snapshot: Any,
    s_cells: Iterable[int],
    *,
    collar_layers: int,
    allowed_cells: Iterable[int] | None = None,
    quotient_neighbor_pairs: Iterable[Sequence[int]] = (),
    tolerance: float = 1.0e-12,
) -> GeometricCollar:
    """Construct a mixed-depth collar from rectangle-contact layers."""

    if int(collar_layers) < 0:
        raise ValueError("collar_layers must be nonnegative")
    if not np.isfinite(tolerance) or tolerance < 0.0:
        raise ValueError("tolerance must be finite and nonnegative")
    rectangles = _rectangles(snapshot)
    all_cells = frozenset(range(len(rectangles)))
    allowed = (
        all_cells
        if allowed_cells is None
        else frozenset(int(cell) for cell in allowed_cells)
    )
    unknown_allowed = allowed - all_cells
    if unknown_allowed:
        raise ValueError(
            f"allowed_cells contains unknown ids {sorted(unknown_allowed)!r}"
        )
    seed = frozenset(int(cell) for cell in s_cells)
    if not seed:
        raise ValueError("the Morse seed S must be nonempty")
    if not seed <= allowed:
        raise ValueError("the Morse seed S must be contained in allowed_cells")

    same_chart_edges, contact_algorithm = _same_chart_contact_edges(
        tuple(snapshot.cells),
        rectangles,
        allowed,
        tolerance=float(tolerance),
    )
    quotient_edges = _normalized_pairs(
        quotient_neighbor_pairs,
        name="quotient_neighbor_pairs",
    )
    invalid_quotient = [
        edge for edge in quotient_edges if not set(edge) <= allowed
    ]
    if invalid_quotient:
        raise ValueError(
            "quotient neighbor pairs must lie in allowed_cells: "
            f"{invalid_quotient[:12]!r}"
        )
    adjacency: dict[int, set[int]] = {cell: set() for cell in allowed}
    for source, target in (*same_chart_edges, *quotient_edges):
        adjacency[source].add(target)
        adjacency[target].add(source)

    n_cells = set(seed)
    frontier = set(seed)
    shells: list[tuple[int, ...]] = [tuple(sorted(seed))]
    for _ in range(int(collar_layers)):
        next_frontier = {
            neighbor
            for source in frontier
            for neighbor in adjacency[source]
            if neighbor not in n_cells
        }
        shells.append(tuple(sorted(next_frontier)))
        n_cells.update(next_frontier)
        frontier = next_frontier

    chart_dimensions: dict[int, int] = {}
    width_vectors: dict[int, set[tuple[float, ...]]] = {}
    for rectangle in rectangles:
        if rectangle.index not in allowed:
            continue
        chart_dimensions[rectangle.chart_id] = rectangle.dimension
        width_vectors.setdefault(rectangle.chart_id, set()).add(
            tuple(round(width, 14) for width in rectangle.width)
        )
    frozen_widths = {
        chart: tuple(sorted(vectors)) for chart, vectors in width_vectors.items()
    }
    return GeometricCollar(
        n_cells=frozenset(n_cells),
        shells=tuple(shells),
        neighbor_edges=same_chart_edges,
        quotient_neighbor_edges=quotient_edges,
        allowed_cells=allowed,
        chart_dimensions=MappingProxyType(chart_dimensions),
        width_vectors_by_chart=MappingProxyType(frozen_widths),
        mixed_cell_sizes=any(len(vectors) > 1 for vectors in frozen_widths.values()),
        contact_algorithm=contact_algorithm,
        tolerance=float(tolerance),
    )


def _recurrent_components(
    adjacency: Sequence[Sequence[int]],
    cells: frozenset[int],
) -> tuple[tuple[int, ...], ...]:
    graph = nx.DiGraph()
    graph.add_nodes_from(cells)
    graph.add_edges_from(
        (source, target)
        for source in cells
        for target in adjacency[source]
        if target in cells
    )
    components = []
    for raw_component in nx.strongly_connected_components(graph):
        component = tuple(sorted(int(cell) for cell in raw_component))
        if len(component) > 1 or graph.has_edge(component[0], component[0]):
            components.append(component)
    return tuple(sorted(components, key=lambda component: component[0]))


def construct_exit_aware_local_index_pair(
    snapshot: Any,
    specification: ExitAwareLocalIndexInput,
    *,
    persistence_schema: str | None = None,
    relation_sha256: str | None = None,
    tolerance: float = 1.0e-12,
) -> ExitAwareLocalIndexPairCertificate:
    """Construct and certify the least exit-aware pair for one Morse SCC."""

    cells = tuple(snapshot.cells)
    adjacency = tuple(tuple(int(target) for target in cell.image) for cell in cells)
    cell_ids = frozenset(range(len(cells)))
    invalid_targets = sorted(
        {
            target
            for image in adjacency
            for target in image
            if target not in cell_ids
        }
    )
    if invalid_targets:
        raise ValueError(f"relation contains unknown target ids {invalid_targets!r}")
    unknown_flag_sources = set(specification.open_exit_flags) - cell_ids
    if unknown_flag_sources:
        raise ValueError(
            "open-exit flags contain unknown source ids "
            f"{sorted(unknown_flag_sources)!r}"
        )
    s_cells = frozenset(
        int(cell) for cell in snapshot.morse_set(specification.morse_node)
    )
    collar = build_geometric_collar(
        snapshot,
        s_cells,
        collar_layers=specification.collar_layers,
        allowed_cells=specification.allowed_cells,
        quotient_neighbor_pairs=specification.quotient_neighbor_pairs,
        tolerance=tolerance,
    )
    n_cells = collar.n_cells
    missing_flags = tuple(
        sorted(n_cells - set(specification.open_exit_flags))
    )
    ambient_exits = tuple(
        sorted(
            source
            for source in n_cells
            if specification.open_exit_flags.get(source, True)
        )
    )
    unevaluated = tuple(
        sorted(
            source
            for source in n_cells
            if not bool(getattr(cells[source], "relation_evaluated", True))
        )
    )
    relation_exit_edges = tuple(
        (source, tuple(sorted(set(adjacency[source]) - n_cells)))
        for source in sorted(n_cells)
        if set(adjacency[source]) - n_cells
    )
    relation_exit_sources = {source for source, _targets in relation_exit_edges}
    l_cells = set(ambient_exits) | relation_exit_sources | set(unevaluated)
    initial_l = frozenset(l_cells)

    closure_rounds: list[tuple[int, ...]] = []
    while True:
        added = {
            target
            for source in l_cells
            for target in adjacency[source]
            if target in n_cells and target not in l_cells
        }
        if not added:
            break
        ordered = tuple(sorted(added))
        closure_rounds.append(ordered)
        l_cells.update(added)
    frozen_l = frozenset(l_cells)
    core = n_cells - frozen_l

    first_violations = tuple(
        (source, tuple(sorted(set(adjacency[source]) - n_cells)))
        for source in sorted(core)
        if set(adjacency[source]) - n_cells
    )
    second_violations = tuple(
        (source, tuple(sorted((set(adjacency[source]) & n_cells) - frozen_l)))
        for source in sorted(frozen_l)
        if (set(adjacency[source]) & n_cells) - frozen_l
    )
    recurrent = _recurrent_components(adjacency, core)
    s_tuple = tuple(sorted(s_cells))
    s_recurrent = s_tuple in recurrent
    unexpected = tuple(component for component in recurrent if component != s_tuple)

    return ExitAwareLocalIndexPairCertificate(
        model=str(snapshot.model),
        depth=int(snapshot.depth),
        t_star=float(snapshot.t_star),
        relation_scope=str(getattr(snapshot, "relation_scope", "persisted_relation")),
        persistence_schema=persistence_schema,
        relation_sha256=relation_sha256,
        morse_node=specification.morse_node,
        specification_metadata=MappingProxyType(dict(specification.metadata)),
        s_cells=s_cells,
        collar=collar,
        ambient_exit_sources=ambient_exits,
        relation_exit_edges=relation_exit_edges,
        unevaluated_n_sources=unevaluated,
        missing_open_exit_flags=missing_flags,
        initial_l_cells=initial_l,
        closure_rounds=tuple(closure_rounds),
        l_cells=frozen_l,
        first_condition_violations=first_violations,
        second_condition_violations=second_violations,
        s_intersection_l=tuple(sorted(s_cells & frozen_l)),
        recurrent_components_in_core=recurrent,
        unexpected_recurrent_components=unexpected,
        s_is_recurrent_component=s_recurrent,
        whole_cell_outer_enclosure_certified=bool(
            getattr(snapshot, "whole_cell_outer_enclosure_certified", False)
        ),
    )


__all__ = [
    "EXIT_AWARE_LOCAL_INDEX_INPUT_SCHEMA",
    "EXIT_AWARE_LOCAL_INDEX_CERTIFICATE_SCHEMA",
    "GARCIA_WALKER_OPEN_EXIT_RELATION_SCHEMA",
    "ExitAwareLocalIndexInput",
    "LoadedExitAwareRelation",
    "GeometricCollar",
    "ExitAwareLocalIndexPairCertificate",
    "sha256_file",
    "load_exit_aware_relation",
    "merge_relation_inputs",
    "build_geometric_collar",
    "construct_exit_aware_local_index_pair",
]
